// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/cdkey"
)

// CdKeyCreate is the builder for creating a CdKey entity.
type CdKeyCreate struct {
	config
	mutation *CdKeyMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *CdKeyCreate) SetCreatedAt(v time.Time) *CdKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CdKeyCreate) SetNillableCreatedAt(v *time.Time) *CdKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CdKeyCreate) SetUpdatedAt(v time.Time) *CdKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CdKeyCreate) SetNillableUpdatedAt(v *time.Time) *CdKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetKey sets the "key" field.
func (_c *CdKeyCreate) SetKey(v string) *CdKeyCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetCount sets the "count" field.
func (_c *CdKeyCreate) SetCount(v int32) *CdKeyCreate {
	_c.mutation.SetCount(v)
	return _c
}

// SetIsEnable sets the "is_enable" field.
func (_c *CdKeyCreate) SetIsEnable(v bool) *CdKeyCreate {
	_c.mutation.SetIsEnable(v)
	return _c
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_c *CdKeyCreate) SetNillableIsEnable(v *bool) *CdKeyCreate {
	if v != nil {
		_c.SetIsEnable(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CdKeyCreate) SetID(v int64) *CdKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CdKeyMutation object of the builder.
func (_c *CdKeyCreate) Mutation() *CdKeyMutation {
	return _c.mutation
}

// Save creates the CdKey in the database.
func (_c *CdKeyCreate) Save(ctx context.Context) (*CdKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CdKeyCreate) SaveX(ctx context.Context) *CdKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CdKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CdKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CdKeyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cdkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cdkey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsEnable(); !ok {
		v := cdkey.DefaultIsEnable
		_c.mutation.SetIsEnable(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CdKeyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CdKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CdKey.updated_at"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "CdKey.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := cdkey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "CdKey.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "CdKey.count"`)}
	}
	if _, ok := _c.mutation.IsEnable(); !ok {
		return &ValidationError{Name: "is_enable", err: errors.New(`ent: missing required field "CdKey.is_enable"`)}
	}
	return nil
}

func (_c *CdKeyCreate) sqlSave(ctx context.Context) (*CdKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CdKeyCreate) createSpec() (*CdKey, *sqlgraph.CreateSpec) {
	var (
		_node = &CdKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cdkey.Table, sqlgraph.NewFieldSpec(cdkey.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cdkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cdkey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(cdkey.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Count(); ok {
		_spec.SetField(cdkey.FieldCount, field.TypeInt32, value)
		_node.Count = value
	}
	if value, ok := _c.mutation.IsEnable(); ok {
		_spec.SetField(cdkey.FieldIsEnable, field.TypeBool, value)
		_node.IsEnable = value
	}
	return _node, _spec
}

// CdKeyCreateBulk is the builder for creating many CdKey entities in bulk.
type CdKeyCreateBulk struct {
	config
	err      error
	builders []*CdKeyCreate
}

// Save creates the CdKey entities in the database.
func (_c *CdKeyCreateBulk) Save(ctx context.Context) ([]*CdKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CdKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CdKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CdKeyCreateBulk) SaveX(ctx context.Context) []*CdKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CdKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CdKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
