// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/env"
)

// Env is the model entity for the Env schema.
type Env struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID int64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 名称
	Name string `json:"name,omitempty"`
	// 备注
	Remarks *string `json:"remarks,omitempty"`
	// 负载数量
	Quantity int32 `json:"quantity,omitempty"`
	// 匹配正则
	Regex *string `json:"regex,omitempty"`
	// 模式
	Mode int32 `json:"mode,omitempty"`
	// 匹配正则[更新]
	RegexUpdate *string `json:"regex_update,omitempty"`
	// 是否自动启用提交的变量
	IsAutoEnvEnable bool `json:"is_auto_env_enable,omitempty"`
	// 是否启用KEY
	EnableKey bool `json:"enable_key,omitempty"`
	// 单次消耗卡密额度
	CdkLimit int32 `json:"cdk_limit,omitempty"`
	// 是否提示
	IsPrompt bool `json:"is_prompt,omitempty"`
	// 提示等级
	PromptLevel *string `json:"prompt_level,omitempty"`
	// 提示内容
	PromptContent *string `json:"prompt_content,omitempty"`
	// 是否启用
	IsEnable bool `json:"is_enable,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EnvQuery when eager-loading is set.
	Edges        EnvEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EnvEdges holds the relations/edges for other nodes in the graph.
type EnvEdges struct {
	// Panels holds the value of the panels edge.
	Panels []*Panel `json:"panels,omitempty"`
	// EnvPlugins holds the value of the env_plugins edge.
	EnvPlugins []*EnvPlugin `json:"env_plugins,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PanelsOrErr returns the Panels value or an error if the edge
// was not loaded in eager-loading.
func (e EnvEdges) PanelsOrErr() ([]*Panel, error) {
	if e.loadedTypes[0] {
		return e.Panels, nil
	}
	return nil, &NotLoadedError{edge: "panels"}
}

// EnvPluginsOrErr returns the EnvPlugins value or an error if the edge
// was not loaded in eager-loading.
func (e EnvEdges) EnvPluginsOrErr() ([]*EnvPlugin, error) {
	if e.loadedTypes[1] {
		return e.EnvPlugins, nil
	}
	return nil, &NotLoadedError{edge: "env_plugins"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Env) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case env.FieldIsAutoEnvEnable, env.FieldEnableKey, env.FieldIsPrompt, env.FieldIsEnable:
			values[i] = new(sql.NullBool)
		case env.FieldID, env.FieldQuantity, env.FieldMode, env.FieldCdkLimit:
			values[i] = new(sql.NullInt64)
		case env.FieldName, env.FieldRemarks, env.FieldRegex, env.FieldRegexUpdate, env.FieldPromptLevel, env.FieldPromptContent:
			values[i] = new(sql.NullString)
		case env.FieldCreatedAt, env.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Env fields.
func (_m *Env) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case env.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case env.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case env.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case env.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case env.FieldRemarks:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remarks", values[i])
			} else if value.Valid {
				_m.Remarks = new(string)
				*_m.Remarks = value.String
			}
		case env.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = int32(value.Int64)
			}
		case env.FieldRegex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field regex", values[i])
			} else if value.Valid {
				_m.Regex = new(string)
				*_m.Regex = value.String
			}
		case env.FieldMode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = int32(value.Int64)
			}
		case env.FieldRegexUpdate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field regex_update", values[i])
			} else if value.Valid {
				_m.RegexUpdate = new(string)
				*_m.RegexUpdate = value.String
			}
		case env.FieldIsAutoEnvEnable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_auto_env_enable", values[i])
			} else if value.Valid {
				_m.IsAutoEnvEnable = value.Bool
			}
		case env.FieldEnableKey:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enable_key", values[i])
			} else if value.Valid {
				_m.EnableKey = value.Bool
			}
		case env.FieldCdkLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cdk_limit", values[i])
			} else if value.Valid {
				_m.CdkLimit = int32(value.Int64)
			}
		case env.FieldIsPrompt:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_prompt", values[i])
			} else if value.Valid {
				_m.IsPrompt = value.Bool
			}
		case env.FieldPromptLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_level", values[i])
			} else if value.Valid {
				_m.PromptLevel = new(string)
				*_m.PromptLevel = value.String
			}
		case env.FieldPromptContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_content", values[i])
			} else if value.Valid {
				_m.PromptContent = new(string)
				*_m.PromptContent = value.String
			}
		case env.FieldIsEnable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enable", values[i])
			} else if value.Valid {
				_m.IsEnable = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Env.
// This includes values selected through modifiers, order, etc.
func (_m *Env) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPanels queries the "panels" edge of the Env entity.
func (_m *Env) QueryPanels() *PanelQuery {
	return NewEnvClient(_m.config).QueryPanels(_m)
}

// QueryEnvPlugins queries the "env_plugins" edge of the Env entity.
func (_m *Env) QueryEnvPlugins() *EnvPluginQuery {
	return NewEnvClient(_m.config).QueryEnvPlugins(_m)
}

// Update returns a builder for updating this Env.
// Note that you need to call Env.Unwrap() before calling this method if this Env
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Env) Update() *EnvUpdateOne {
	return NewEnvClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Env entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Env) Unwrap() *Env {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Env is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Env) String() string {
	var builder strings.Builder
	builder.WriteString("Env(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Remarks; v != nil {
		builder.WriteString("remarks=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	if v := _m.Regex; v != nil {
		builder.WriteString("regex=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mode))
	builder.WriteString(", ")
	if v := _m.RegexUpdate; v != nil {
		builder.WriteString("regex_update=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_auto_env_enable=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsAutoEnvEnable))
	builder.WriteString(", ")
	builder.WriteString("enable_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnableKey))
	builder.WriteString(", ")
	builder.WriteString("cdk_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.CdkLimit))
	builder.WriteString(", ")
	builder.WriteString("is_prompt=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPrompt))
	builder.WriteString(", ")
	if v := _m.PromptLevel; v != nil {
		builder.WriteString("prompt_level=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PromptContent; v != nil {
		builder.WriteString("prompt_content=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_enable=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsEnable))
	builder.WriteByte(')')
	return builder.String()
}

// Envs is a parsable slice of Env.
type Envs []*Env
