// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/env"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/envplugin"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/panel"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/predicate"
)

// EnvUpdate is the builder for updating Env entities.
type EnvUpdate struct {
	config
	hooks    []Hook
	mutation *EnvMutation
}

// Where appends a list predicates to the EnvUpdate builder.
func (_u *EnvUpdate) Where(ps ...predicate.Env) *EnvUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnvUpdate) SetUpdatedAt(v time.Time) *EnvUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *EnvUpdate) SetName(v string) *EnvUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnvUpdate) SetNillableName(v *string) *EnvUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRemarks sets the "remarks" field.
func (_u *EnvUpdate) SetRemarks(v string) *EnvUpdate {
	_u.mutation.SetRemarks(v)
	return _u
}

// SetNillableRemarks sets the "remarks" field if the given value is not nil.
func (_u *EnvUpdate) SetNillableRemarks(v *string) *EnvUpdate {
	if v != nil {
		_u.SetRemarks(*v)
	}
	return _u
}

// ClearRemarks clears the value of the "remarks" field.
func (_u *EnvUpdate) ClearRemarks() *EnvUpdate {
	_u.mutation.ClearRemarks()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *EnvUpdate) SetQuantity(v int32) *EnvUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *EnvUpdate) SetNillableQuantity(v *int32) *EnvUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *EnvUpdate) AddQuantity(v int32) *EnvUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetRegex sets the "regex" field.
func (_u *EnvUpdate) SetRegex(v string) *EnvUpdate {
	_u.mutation.SetRegex(v)
	return _u
}

// SetNillableRegex sets the "regex" field if the given value is not nil.
func (_u *EnvUpdate) SetNillableRegex(v *string) *EnvUpdate {
	if v != nil {
		_u.SetRegex(*v)
	}
	return _u
}

// ClearRegex clears the value of the "regex" field.
func (_u *EnvUpdate) ClearRegex() *EnvUpdate {
	_u.mutation.ClearRegex()
	return _u
}

// SetMode sets the "mode" field.
func (_u *EnvUpdate) SetMode(v int32) *EnvUpdate {
	_u.mutation.ResetMode()
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *EnvUpdate) SetNillableMode(v *int32) *EnvUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// AddMode adds value to the "mode" field.
func (_u *EnvUpdate) AddMode(v int32) *EnvUpdate {
	_u.mutation.AddMode(v)
	return _u
}

// SetRegexUpdate sets the "regex_update" field.
func (_u *EnvUpdate) SetRegexUpdate(v string) *EnvUpdate {
	_u.mutation.SetRegexUpdate(v)
	return _u
}

// SetNillableRegexUpdate sets the "regex_update" field if the given value is not nil.
func (_u *EnvUpdate) SetNillableRegexUpdate(v *string) *EnvUpdate {
	if v != nil {
		_u.SetRegexUpdate(*v)
	}
	return _u
}

// ClearRegexUpdate clears the value of the "regex_update" field.
func (_u *EnvUpdate) ClearRegexUpdate() *EnvUpdate {
	_u.mutation.ClearRegexUpdate()
	return _u
}

// SetIsAutoEnvEnable sets the "is_auto_env_enable" field.
func (_u *EnvUpdate) SetIsAutoEnvEnable(v bool) *EnvUpdate {
	_u.mutation.SetIsAutoEnvEnable(v)
	return _u
}

// SetNillableIsAutoEnvEnable sets the "is_auto_env_enable" field if the given value is not nil.
func (_u *EnvUpdate) SetNillableIsAutoEnvEnable(v *bool) *EnvUpdate {
	if v != nil {
		_u.SetIsAutoEnvEnable(*v)
	}
	return _u
}

// SetEnableKey sets the "enable_key" field.
func (_u *EnvUpdate) SetEnableKey(v bool) *EnvUpdate {
	_u.mutation.SetEnableKey(v)
	return _u
}

// SetNillableEnableKey sets the "enable_key" field if the given value is not nil.
func (_u *EnvUpdate) SetNillableEnableKey(v *bool) *EnvUpdate {
	if v != nil {
		_u.SetEnableKey(*v)
	}
	return _u
}

// SetCdkLimit sets the "cdk_limit" field.
func (_u *EnvUpdate) SetCdkLimit(v int32) *EnvUpdate {
	_u.mutation.ResetCdkLimit()
	_u.mutation.SetCdkLimit(v)
	return _u
}

// SetNillableCdkLimit sets the "cdk_limit" field if the given value is not nil.
func (_u *EnvUpdate) SetNillableCdkLimit(v *int32) *EnvUpdate {
	if v != nil {
		_u.SetCdkLimit(*v)
	}
	return _u
}

// AddCdkLimit adds value to the "cdk_limit" field.
func (_u *EnvUpdate) AddCdkLimit(v int32) *EnvUpdate {
	_u.mutation.AddCdkLimit(v)
	return _u
}

// SetIsPrompt sets the "is_prompt" field.
func (_u *EnvUpdate) SetIsPrompt(v bool) *EnvUpdate {
	_u.mutation.SetIsPrompt(v)
	return _u
}

// SetNillableIsPrompt sets the "is_prompt" field if the given value is not nil.
func (_u *EnvUpdate) SetNillableIsPrompt(v *bool) *EnvUpdate {
	if v != nil {
		_u.SetIsPrompt(*v)
	}
	return _u
}

// SetPromptLevel sets the "prompt_level" field.
func (_u *EnvUpdate) SetPromptLevel(v string) *EnvUpdate {
	_u.mutation.SetPromptLevel(v)
	return _u
}

// SetNillablePromptLevel sets the "prompt_level" field if the given value is not nil.
func (_u *EnvUpdate) SetNillablePromptLevel(v *string) *EnvUpdate {
	if v != nil {
		_u.SetPromptLevel(*v)
	}
	return _u
}

// ClearPromptLevel clears the value of the "prompt_level" field.
func (_u *EnvUpdate) ClearPromptLevel() *EnvUpdate {
	_u.mutation.ClearPromptLevel()
	return _u
}

// SetPromptContent sets the "prompt_content" field.
func (_u *EnvUpdate) SetPromptContent(v string) *EnvUpdate {
	_u.mutation.SetPromptContent(v)
	return _u
}

// SetNillablePromptContent sets the "prompt_content" field if the given value is not nil.
func (_u *EnvUpdate) SetNillablePromptContent(v *string) *EnvUpdate {
	if v != nil {
		_u.SetPromptContent(*v)
	}
	return _u
}

// ClearPromptContent clears the value of the "prompt_content" field.
func (_u *EnvUpdate) ClearPromptContent() *EnvUpdate {
	_u.mutation.ClearPromptContent()
	return _u
}

// SetIsEnable sets the "is_enable" field.
func (_u *EnvUpdate) SetIsEnable(v bool) *EnvUpdate {
	_u.mutation.SetIsEnable(v)
	return _u
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_u *EnvUpdate) SetNillableIsEnable(v *bool) *EnvUpdate {
	if v != nil {
		_u.SetIsEnable(*v)
	}
	return _u
}

// AddPanelIDs adds the "panels" edge to the Panel entity by IDs.
func (_u *EnvUpdate) AddPanelIDs(ids ...int64) *EnvUpdate {
	_u.mutation.AddPanelIDs(ids...)
	return _u
}

// AddPanels adds the "panels" edges to the Panel entity.
func (_u *EnvUpdate) AddPanels(v ...*Panel) *EnvUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPanelIDs(ids...)
}

// AddEnvPluginIDs adds the "env_plugins" edge to the EnvPlugin entity by IDs.
func (_u *EnvUpdate) AddEnvPluginIDs(ids ...int64) *EnvUpdate {
	_u.mutation.AddEnvPluginIDs(ids...)
	return _u
}

// AddEnvPlugins adds the "env_plugins" edges to the EnvPlugin entity.
func (_u *EnvUpdate) AddEnvPlugins(v ...*EnvPlugin) *EnvUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnvPluginIDs(ids...)
}

// Mutation returns the EnvMutation object of the builder.
func (_u *EnvUpdate) Mutation() *EnvMutation {
	return _u.mutation
}

// ClearPanels clears all "panels" edges to the Panel entity.
func (_u *EnvUpdate) ClearPanels() *EnvUpdate {
	_u.mutation.ClearPanels()
	return _u
}

// RemovePanelIDs removes the "panels" edge to Panel entities by IDs.
func (_u *EnvUpdate) RemovePanelIDs(ids ...int64) *EnvUpdate {
	_u.mutation.RemovePanelIDs(ids...)
	return _u
}

// RemovePanels removes "panels" edges to Panel entities.
func (_u *EnvUpdate) RemovePanels(v ...*Panel) *EnvUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePanelIDs(ids...)
}

// ClearEnvPlugins clears all "env_plugins" edges to the EnvPlugin entity.
func (_u *EnvUpdate) ClearEnvPlugins() *EnvUpdate {
	_u.mutation.ClearEnvPlugins()
	return _u
}

// RemoveEnvPluginIDs removes the "env_plugins" edge to EnvPlugin entities by IDs.
func (_u *EnvUpdate) RemoveEnvPluginIDs(ids ...int64) *EnvUpdate {
	_u.mutation.RemoveEnvPluginIDs(ids...)
	return _u
}

// RemoveEnvPlugins removes "env_plugins" edges to EnvPlugin entities.
func (_u *EnvUpdate) RemoveEnvPlugins(v ...*EnvPlugin) *EnvUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnvPluginIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnvUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnvUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := env.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := env.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Env.name": %w`, err)}
		}
	}
	return nil
}

func (_u *EnvUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(env.Table, env.Columns, sqlgraph.NewFieldSpec(env.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(env.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(env.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Remarks(); ok {
		_spec.SetField(env.FieldRemarks, field.TypeString, value)
	}
	if _u.mutation.RemarksCleared() {
		_spec.ClearField(env.FieldRemarks, field.TypeString)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(env.FieldQuantity, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(env.FieldQuantity, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Regex(); ok {
		_spec.SetField(env.FieldRegex, field.TypeString, value)
	}
	if _u.mutation.RegexCleared() {
		_spec.ClearField(env.FieldRegex, field.TypeString)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(env.FieldMode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMode(); ok {
		_spec.AddField(env.FieldMode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.RegexUpdate(); ok {
		_spec.SetField(env.FieldRegexUpdate, field.TypeString, value)
	}
	if _u.mutation.RegexUpdateCleared() {
		_spec.ClearField(env.FieldRegexUpdate, field.TypeString)
	}
	if value, ok := _u.mutation.IsAutoEnvEnable(); ok {
		_spec.SetField(env.FieldIsAutoEnvEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableKey(); ok {
		_spec.SetField(env.FieldEnableKey, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CdkLimit(); ok {
		_spec.SetField(env.FieldCdkLimit, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedCdkLimit(); ok {
		_spec.AddField(env.FieldCdkLimit, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.IsPrompt(); ok {
		_spec.SetField(env.FieldIsPrompt, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PromptLevel(); ok {
		_spec.SetField(env.FieldPromptLevel, field.TypeString, value)
	}
	if _u.mutation.PromptLevelCleared() {
		_spec.ClearField(env.FieldPromptLevel, field.TypeString)
	}
	if value, ok := _u.mutation.PromptContent(); ok {
		_spec.SetField(env.FieldPromptContent, field.TypeString, value)
	}
	if _u.mutation.PromptContentCleared() {
		_spec.ClearField(env.FieldPromptContent, field.TypeString)
	}
	if value, ok := _u.mutation.IsEnable(); ok {
		_spec.SetField(env.FieldIsEnable, field.TypeBool, value)
	}
	if _u.mutation.PanelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   env.PanelsTable,
			Columns: env.PanelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(panel.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPanelsIDs(); len(nodes) > 0 && !_u.mutation.PanelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   env.PanelsTable,
			Columns: env.PanelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(panel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PanelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   env.PanelsTable,
			Columns: env.PanelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(panel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnvPluginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   env.EnvPluginsTable,
			Columns: []string{env.EnvPluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envplugin.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnvPluginsIDs(); len(nodes) > 0 && !_u.mutation.EnvPluginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   env.EnvPluginsTable,
			Columns: []string{env.EnvPluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envplugin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvPluginsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   env.EnvPluginsTable,
			Columns: []string{env.EnvPluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envplugin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{env.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnvUpdateOne is the builder for updating a single Env entity.
type EnvUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnvMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnvUpdateOne) SetUpdatedAt(v time.Time) *EnvUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *EnvUpdateOne) SetName(v string) *EnvUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillableName(v *string) *EnvUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRemarks sets the "remarks" field.
func (_u *EnvUpdateOne) SetRemarks(v string) *EnvUpdateOne {
	_u.mutation.SetRemarks(v)
	return _u
}

// SetNillableRemarks sets the "remarks" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillableRemarks(v *string) *EnvUpdateOne {
	if v != nil {
		_u.SetRemarks(*v)
	}
	return _u
}

// ClearRemarks clears the value of the "remarks" field.
func (_u *EnvUpdateOne) ClearRemarks() *EnvUpdateOne {
	_u.mutation.ClearRemarks()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *EnvUpdateOne) SetQuantity(v int32) *EnvUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillableQuantity(v *int32) *EnvUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *EnvUpdateOne) AddQuantity(v int32) *EnvUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetRegex sets the "regex" field.
func (_u *EnvUpdateOne) SetRegex(v string) *EnvUpdateOne {
	_u.mutation.SetRegex(v)
	return _u
}

// SetNillableRegex sets the "regex" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillableRegex(v *string) *EnvUpdateOne {
	if v != nil {
		_u.SetRegex(*v)
	}
	return _u
}

// ClearRegex clears the value of the "regex" field.
func (_u *EnvUpdateOne) ClearRegex() *EnvUpdateOne {
	_u.mutation.ClearRegex()
	return _u
}

// SetMode sets the "mode" field.
func (_u *EnvUpdateOne) SetMode(v int32) *EnvUpdateOne {
	_u.mutation.ResetMode()
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillableMode(v *int32) *EnvUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// AddMode adds value to the "mode" field.
func (_u *EnvUpdateOne) AddMode(v int32) *EnvUpdateOne {
	_u.mutation.AddMode(v)
	return _u
}

// SetRegexUpdate sets the "regex_update" field.
func (_u *EnvUpdateOne) SetRegexUpdate(v string) *EnvUpdateOne {
	_u.mutation.SetRegexUpdate(v)
	return _u
}

// SetNillableRegexUpdate sets the "regex_update" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillableRegexUpdate(v *string) *EnvUpdateOne {
	if v != nil {
		_u.SetRegexUpdate(*v)
	}
	return _u
}

// ClearRegexUpdate clears the value of the "regex_update" field.
func (_u *EnvUpdateOne) ClearRegexUpdate() *EnvUpdateOne {
	_u.mutation.ClearRegexUpdate()
	return _u
}

// SetIsAutoEnvEnable sets the "is_auto_env_enable" field.
func (_u *EnvUpdateOne) SetIsAutoEnvEnable(v bool) *EnvUpdateOne {
	_u.mutation.SetIsAutoEnvEnable(v)
	return _u
}

// SetNillableIsAutoEnvEnable sets the "is_auto_env_enable" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillableIsAutoEnvEnable(v *bool) *EnvUpdateOne {
	if v != nil {
		_u.SetIsAutoEnvEnable(*v)
	}
	return _u
}

// SetEnableKey sets the "enable_key" field.
func (_u *EnvUpdateOne) SetEnableKey(v bool) *EnvUpdateOne {
	_u.mutation.SetEnableKey(v)
	return _u
}

// SetNillableEnableKey sets the "enable_key" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillableEnableKey(v *bool) *EnvUpdateOne {
	if v != nil {
		_u.SetEnableKey(*v)
	}
	return _u
}

// SetCdkLimit sets the "cdk_limit" field.
func (_u *EnvUpdateOne) SetCdkLimit(v int32) *EnvUpdateOne {
	_u.mutation.ResetCdkLimit()
	_u.mutation.SetCdkLimit(v)
	return _u
}

// SetNillableCdkLimit sets the "cdk_limit" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillableCdkLimit(v *int32) *EnvUpdateOne {
	if v != nil {
		_u.SetCdkLimit(*v)
	}
	return _u
}

// AddCdkLimit adds value to the "cdk_limit" field.
func (_u *EnvUpdateOne) AddCdkLimit(v int32) *EnvUpdateOne {
	_u.mutation.AddCdkLimit(v)
	return _u
}

// SetIsPrompt sets the "is_prompt" field.
func (_u *EnvUpdateOne) SetIsPrompt(v bool) *EnvUpdateOne {
	_u.mutation.SetIsPrompt(v)
	return _u
}

// SetNillableIsPrompt sets the "is_prompt" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillableIsPrompt(v *bool) *EnvUpdateOne {
	if v != nil {
		_u.SetIsPrompt(*v)
	}
	return _u
}

// SetPromptLevel sets the "prompt_level" field.
func (_u *EnvUpdateOne) SetPromptLevel(v string) *EnvUpdateOne {
	_u.mutation.SetPromptLevel(v)
	return _u
}

// SetNillablePromptLevel sets the "prompt_level" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillablePromptLevel(v *string) *EnvUpdateOne {
	if v != nil {
		_u.SetPromptLevel(*v)
	}
	return _u
}

// ClearPromptLevel clears the value of the "prompt_level" field.
func (_u *EnvUpdateOne) ClearPromptLevel() *EnvUpdateOne {
	_u.mutation.ClearPromptLevel()
	return _u
}

// SetPromptContent sets the "prompt_content" field.
func (_u *EnvUpdateOne) SetPromptContent(v string) *EnvUpdateOne {
	_u.mutation.SetPromptContent(v)
	return _u
}

// SetNillablePromptContent sets the "prompt_content" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillablePromptContent(v *string) *EnvUpdateOne {
	if v != nil {
		_u.SetPromptContent(*v)
	}
	return _u
}

// ClearPromptContent clears the value of the "prompt_content" field.
func (_u *EnvUpdateOne) ClearPromptContent() *EnvUpdateOne {
	_u.mutation.ClearPromptContent()
	return _u
}

// SetIsEnable sets the "is_enable" field.
func (_u *EnvUpdateOne) SetIsEnable(v bool) *EnvUpdateOne {
	_u.mutation.SetIsEnable(v)
	return _u
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_u *EnvUpdateOne) SetNillableIsEnable(v *bool) *EnvUpdateOne {
	if v != nil {
		_u.SetIsEnable(*v)
	}
	return _u
}

// AddPanelIDs adds the "panels" edge to the Panel entity by IDs.
func (_u *EnvUpdateOne) AddPanelIDs(ids ...int64) *EnvUpdateOne {
	_u.mutation.AddPanelIDs(ids...)
	return _u
}

// AddPanels adds the "panels" edges to the Panel entity.
func (_u *EnvUpdateOne) AddPanels(v ...*Panel) *EnvUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPanelIDs(ids...)
}

// AddEnvPluginIDs adds the "env_plugins" edge to the EnvPlugin entity by IDs.
func (_u *EnvUpdateOne) AddEnvPluginIDs(ids ...int64) *EnvUpdateOne {
	_u.mutation.AddEnvPluginIDs(ids...)
	return _u
}

// AddEnvPlugins adds the "env_plugins" edges to the EnvPlugin entity.
func (_u *EnvUpdateOne) AddEnvPlugins(v ...*EnvPlugin) *EnvUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnvPluginIDs(ids...)
}

// Mutation returns the EnvMutation object of the builder.
func (_u *EnvUpdateOne) Mutation() *EnvMutation {
	return _u.mutation
}

// ClearPanels clears all "panels" edges to the Panel entity.
func (_u *EnvUpdateOne) ClearPanels() *EnvUpdateOne {
	_u.mutation.ClearPanels()
	return _u
}

// RemovePanelIDs removes the "panels" edge to Panel entities by IDs.
func (_u *EnvUpdateOne) RemovePanelIDs(ids ...int64) *EnvUpdateOne {
	_u.mutation.RemovePanelIDs(ids...)
	return _u
}

// RemovePanels removes "panels" edges to Panel entities.
func (_u *EnvUpdateOne) RemovePanels(v ...*Panel) *EnvUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePanelIDs(ids...)
}

// ClearEnvPlugins clears all "env_plugins" edges to the EnvPlugin entity.
func (_u *EnvUpdateOne) ClearEnvPlugins() *EnvUpdateOne {
	_u.mutation.ClearEnvPlugins()
	return _u
}

// RemoveEnvPluginIDs removes the "env_plugins" edge to EnvPlugin entities by IDs.
func (_u *EnvUpdateOne) RemoveEnvPluginIDs(ids ...int64) *EnvUpdateOne {
	_u.mutation.RemoveEnvPluginIDs(ids...)
	return _u
}

// RemoveEnvPlugins removes "env_plugins" edges to EnvPlugin entities.
func (_u *EnvUpdateOne) RemoveEnvPlugins(v ...*EnvPlugin) *EnvUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnvPluginIDs(ids...)
}

// Where appends a list predicates to the EnvUpdate builder.
func (_u *EnvUpdateOne) Where(ps ...predicate.Env) *EnvUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnvUpdateOne) Select(field string, fields ...string) *EnvUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Env entity.
func (_u *EnvUpdateOne) Save(ctx context.Context) (*Env, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvUpdateOne) SaveX(ctx context.Context) *Env {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnvUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := env.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := env.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Env.name": %w`, err)}
		}
	}
	return nil
}

func (_u *EnvUpdateOne) sqlSave(ctx context.Context) (_node *Env, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(env.Table, env.Columns, sqlgraph.NewFieldSpec(env.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Env.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, env.FieldID)
		for _, f := range fields {
			if !env.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != env.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(env.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(env.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Remarks(); ok {
		_spec.SetField(env.FieldRemarks, field.TypeString, value)
	}
	if _u.mutation.RemarksCleared() {
		_spec.ClearField(env.FieldRemarks, field.TypeString)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(env.FieldQuantity, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(env.FieldQuantity, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Regex(); ok {
		_spec.SetField(env.FieldRegex, field.TypeString, value)
	}
	if _u.mutation.RegexCleared() {
		_spec.ClearField(env.FieldRegex, field.TypeString)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(env.FieldMode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMode(); ok {
		_spec.AddField(env.FieldMode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.RegexUpdate(); ok {
		_spec.SetField(env.FieldRegexUpdate, field.TypeString, value)
	}
	if _u.mutation.RegexUpdateCleared() {
		_spec.ClearField(env.FieldRegexUpdate, field.TypeString)
	}
	if value, ok := _u.mutation.IsAutoEnvEnable(); ok {
		_spec.SetField(env.FieldIsAutoEnvEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableKey(); ok {
		_spec.SetField(env.FieldEnableKey, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CdkLimit(); ok {
		_spec.SetField(env.FieldCdkLimit, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedCdkLimit(); ok {
		_spec.AddField(env.FieldCdkLimit, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.IsPrompt(); ok {
		_spec.SetField(env.FieldIsPrompt, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PromptLevel(); ok {
		_spec.SetField(env.FieldPromptLevel, field.TypeString, value)
	}
	if _u.mutation.PromptLevelCleared() {
		_spec.ClearField(env.FieldPromptLevel, field.TypeString)
	}
	if value, ok := _u.mutation.PromptContent(); ok {
		_spec.SetField(env.FieldPromptContent, field.TypeString, value)
	}
	if _u.mutation.PromptContentCleared() {
		_spec.ClearField(env.FieldPromptContent, field.TypeString)
	}
	if value, ok := _u.mutation.IsEnable(); ok {
		_spec.SetField(env.FieldIsEnable, field.TypeBool, value)
	}
	if _u.mutation.PanelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   env.PanelsTable,
			Columns: env.PanelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(panel.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPanelsIDs(); len(nodes) > 0 && !_u.mutation.PanelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   env.PanelsTable,
			Columns: env.PanelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(panel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PanelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   env.PanelsTable,
			Columns: env.PanelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(panel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnvPluginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   env.EnvPluginsTable,
			Columns: []string{env.EnvPluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envplugin.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnvPluginsIDs(); len(nodes) > 0 && !_u.mutation.EnvPluginsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   env.EnvPluginsTable,
			Columns: []string{env.EnvPluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envplugin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvPluginsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   env.EnvPluginsTable,
			Columns: []string{env.EnvPluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envplugin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Env{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{env.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
