// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/env"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/envplugin"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/plugin"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/predicate"
)

// EnvPluginUpdate is the builder for updating EnvPlugin entities.
type EnvPluginUpdate struct {
	config
	hooks    []Hook
	mutation *EnvPluginMutation
}

// Where appends a list predicates to the EnvPluginUpdate builder.
func (_u *EnvPluginUpdate) Where(ps ...predicate.EnvPlugin) *EnvPluginUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnvPluginUpdate) SetUpdatedAt(v time.Time) *EnvPluginUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEnvID sets the "env_id" field.
func (_u *EnvPluginUpdate) SetEnvID(v int64) *EnvPluginUpdate {
	_u.mutation.SetEnvID(v)
	return _u
}

// SetNillableEnvID sets the "env_id" field if the given value is not nil.
func (_u *EnvPluginUpdate) SetNillableEnvID(v *int64) *EnvPluginUpdate {
	if v != nil {
		_u.SetEnvID(*v)
	}
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *EnvPluginUpdate) SetPluginID(v int64) *EnvPluginUpdate {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *EnvPluginUpdate) SetNillablePluginID(v *int64) *EnvPluginUpdate {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetIsEnable sets the "is_enable" field.
func (_u *EnvPluginUpdate) SetIsEnable(v bool) *EnvPluginUpdate {
	_u.mutation.SetIsEnable(v)
	return _u
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_u *EnvPluginUpdate) SetNillableIsEnable(v *bool) *EnvPluginUpdate {
	if v != nil {
		_u.SetIsEnable(*v)
	}
	return _u
}

// SetExecutionOrder sets the "execution_order" field.
func (_u *EnvPluginUpdate) SetExecutionOrder(v int32) *EnvPluginUpdate {
	_u.mutation.ResetExecutionOrder()
	_u.mutation.SetExecutionOrder(v)
	return _u
}

// SetNillableExecutionOrder sets the "execution_order" field if the given value is not nil.
func (_u *EnvPluginUpdate) SetNillableExecutionOrder(v *int32) *EnvPluginUpdate {
	if v != nil {
		_u.SetExecutionOrder(*v)
	}
	return _u
}

// AddExecutionOrder adds value to the "execution_order" field.
func (_u *EnvPluginUpdate) AddExecutionOrder(v int32) *EnvPluginUpdate {
	_u.mutation.AddExecutionOrder(v)
	return _u
}

// SetConfig sets the "config" field.
func (_u *EnvPluginUpdate) SetConfig(v string) *EnvPluginUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *EnvPluginUpdate) SetNillableConfig(v *string) *EnvPluginUpdate {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *EnvPluginUpdate) ClearConfig() *EnvPluginUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetEnv sets the "env" edge to the Env entity.
func (_u *EnvPluginUpdate) SetEnv(v *Env) *EnvPluginUpdate {
	return _u.SetEnvID(v.ID)
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *EnvPluginUpdate) SetPlugin(v *Plugin) *EnvPluginUpdate {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the EnvPluginMutation object of the builder.
func (_u *EnvPluginUpdate) Mutation() *EnvPluginMutation {
	return _u.mutation
}

// ClearEnv clears the "env" edge to the Env entity.
func (_u *EnvPluginUpdate) ClearEnv() *EnvPluginUpdate {
	_u.mutation.ClearEnv()
	return _u
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *EnvPluginUpdate) ClearPlugin() *EnvPluginUpdate {
	_u.mutation.ClearPlugin()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnvPluginUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvPluginUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnvPluginUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvPluginUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvPluginUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := envplugin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvPluginUpdate) check() error {
	if _u.mutation.EnvCleared() && len(_u.mutation.EnvIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnvPlugin.env"`)
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnvPlugin.plugin"`)
	}
	return nil
}

func (_u *EnvPluginUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(envplugin.Table, envplugin.Columns, sqlgraph.NewFieldSpec(envplugin.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(envplugin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsEnable(); ok {
		_spec.SetField(envplugin.FieldIsEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExecutionOrder(); ok {
		_spec.SetField(envplugin.FieldExecutionOrder, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedExecutionOrder(); ok {
		_spec.AddField(envplugin.FieldExecutionOrder, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(envplugin.FieldConfig, field.TypeString, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(envplugin.FieldConfig, field.TypeString)
	}
	if _u.mutation.EnvCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envplugin.EnvTable,
			Columns: []string{envplugin.EnvColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(env.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envplugin.EnvTable,
			Columns: []string{envplugin.EnvColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(env.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envplugin.PluginTable,
			Columns: []string{envplugin.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envplugin.PluginTable,
			Columns: []string{envplugin.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{envplugin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnvPluginUpdateOne is the builder for updating a single EnvPlugin entity.
type EnvPluginUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnvPluginMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnvPluginUpdateOne) SetUpdatedAt(v time.Time) *EnvPluginUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEnvID sets the "env_id" field.
func (_u *EnvPluginUpdateOne) SetEnvID(v int64) *EnvPluginUpdateOne {
	_u.mutation.SetEnvID(v)
	return _u
}

// SetNillableEnvID sets the "env_id" field if the given value is not nil.
func (_u *EnvPluginUpdateOne) SetNillableEnvID(v *int64) *EnvPluginUpdateOne {
	if v != nil {
		_u.SetEnvID(*v)
	}
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *EnvPluginUpdateOne) SetPluginID(v int64) *EnvPluginUpdateOne {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *EnvPluginUpdateOne) SetNillablePluginID(v *int64) *EnvPluginUpdateOne {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetIsEnable sets the "is_enable" field.
func (_u *EnvPluginUpdateOne) SetIsEnable(v bool) *EnvPluginUpdateOne {
	_u.mutation.SetIsEnable(v)
	return _u
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_u *EnvPluginUpdateOne) SetNillableIsEnable(v *bool) *EnvPluginUpdateOne {
	if v != nil {
		_u.SetIsEnable(*v)
	}
	return _u
}

// SetExecutionOrder sets the "execution_order" field.
func (_u *EnvPluginUpdateOne) SetExecutionOrder(v int32) *EnvPluginUpdateOne {
	_u.mutation.ResetExecutionOrder()
	_u.mutation.SetExecutionOrder(v)
	return _u
}

// SetNillableExecutionOrder sets the "execution_order" field if the given value is not nil.
func (_u *EnvPluginUpdateOne) SetNillableExecutionOrder(v *int32) *EnvPluginUpdateOne {
	if v != nil {
		_u.SetExecutionOrder(*v)
	}
	return _u
}

// AddExecutionOrder adds value to the "execution_order" field.
func (_u *EnvPluginUpdateOne) AddExecutionOrder(v int32) *EnvPluginUpdateOne {
	_u.mutation.AddExecutionOrder(v)
	return _u
}

// SetConfig sets the "config" field.
func (_u *EnvPluginUpdateOne) SetConfig(v string) *EnvPluginUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *EnvPluginUpdateOne) SetNillableConfig(v *string) *EnvPluginUpdateOne {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *EnvPluginUpdateOne) ClearConfig() *EnvPluginUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetEnv sets the "env" edge to the Env entity.
func (_u *EnvPluginUpdateOne) SetEnv(v *Env) *EnvPluginUpdateOne {
	return _u.SetEnvID(v.ID)
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *EnvPluginUpdateOne) SetPlugin(v *Plugin) *EnvPluginUpdateOne {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the EnvPluginMutation object of the builder.
func (_u *EnvPluginUpdateOne) Mutation() *EnvPluginMutation {
	return _u.mutation
}

// ClearEnv clears the "env" edge to the Env entity.
func (_u *EnvPluginUpdateOne) ClearEnv() *EnvPluginUpdateOne {
	_u.mutation.ClearEnv()
	return _u
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *EnvPluginUpdateOne) ClearPlugin() *EnvPluginUpdateOne {
	_u.mutation.ClearPlugin()
	return _u
}

// Where appends a list predicates to the EnvPluginUpdate builder.
func (_u *EnvPluginUpdateOne) Where(ps ...predicate.EnvPlugin) *EnvPluginUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnvPluginUpdateOne) Select(field string, fields ...string) *EnvPluginUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EnvPlugin entity.
func (_u *EnvPluginUpdateOne) Save(ctx context.Context) (*EnvPlugin, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvPluginUpdateOne) SaveX(ctx context.Context) *EnvPlugin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnvPluginUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvPluginUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvPluginUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := envplugin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvPluginUpdateOne) check() error {
	if _u.mutation.EnvCleared() && len(_u.mutation.EnvIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnvPlugin.env"`)
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnvPlugin.plugin"`)
	}
	return nil
}

func (_u *EnvPluginUpdateOne) sqlSave(ctx context.Context) (_node *EnvPlugin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(envplugin.Table, envplugin.Columns, sqlgraph.NewFieldSpec(envplugin.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EnvPlugin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, envplugin.FieldID)
		for _, f := range fields {
			if !envplugin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != envplugin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(envplugin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsEnable(); ok {
		_spec.SetField(envplugin.FieldIsEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExecutionOrder(); ok {
		_spec.SetField(envplugin.FieldExecutionOrder, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedExecutionOrder(); ok {
		_spec.AddField(envplugin.FieldExecutionOrder, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(envplugin.FieldConfig, field.TypeString, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(envplugin.FieldConfig, field.TypeString)
	}
	if _u.mutation.EnvCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envplugin.EnvTable,
			Columns: []string{envplugin.EnvColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(env.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envplugin.EnvTable,
			Columns: []string{envplugin.EnvColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(env.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envplugin.PluginTable,
			Columns: []string{envplugin.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envplugin.PluginTable,
			Columns: []string{envplugin.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EnvPlugin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{envplugin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
