// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/env"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/envplugin"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/plugin"
)

// EnvPlugin is the model entity for the EnvPlugin schema.
type EnvPlugin struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID int64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 环境变量ID
	EnvID int64 `json:"env_id,omitempty"`
	// 插件ID
	PluginID int64 `json:"plugin_id,omitempty"`
	// 是否启用
	IsEnable bool `json:"is_enable,omitempty"`
	// 执行顺序(数字越小越先执行)
	ExecutionOrder int32 `json:"execution_order,omitempty"`
	// 插件配置参数
	Config *string `json:"config,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EnvPluginQuery when eager-loading is set.
	Edges        EnvPluginEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EnvPluginEdges holds the relations/edges for other nodes in the graph.
type EnvPluginEdges struct {
	// Env holds the value of the env edge.
	Env *Env `json:"env,omitempty"`
	// Plugin holds the value of the plugin edge.
	Plugin *Plugin `json:"plugin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// EnvOrErr returns the Env value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EnvPluginEdges) EnvOrErr() (*Env, error) {
	if e.Env != nil {
		return e.Env, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: env.Label}
	}
	return nil, &NotLoadedError{edge: "env"}
}

// PluginOrErr returns the Plugin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EnvPluginEdges) PluginOrErr() (*Plugin, error) {
	if e.Plugin != nil {
		return e.Plugin, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: plugin.Label}
	}
	return nil, &NotLoadedError{edge: "plugin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EnvPlugin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case envplugin.FieldIsEnable:
			values[i] = new(sql.NullBool)
		case envplugin.FieldID, envplugin.FieldEnvID, envplugin.FieldPluginID, envplugin.FieldExecutionOrder:
			values[i] = new(sql.NullInt64)
		case envplugin.FieldConfig:
			values[i] = new(sql.NullString)
		case envplugin.FieldCreatedAt, envplugin.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EnvPlugin fields.
func (_m *EnvPlugin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case envplugin.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case envplugin.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case envplugin.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case envplugin.FieldEnvID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field env_id", values[i])
			} else if value.Valid {
				_m.EnvID = value.Int64
			}
		case envplugin.FieldPluginID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plugin_id", values[i])
			} else if value.Valid {
				_m.PluginID = value.Int64
			}
		case envplugin.FieldIsEnable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enable", values[i])
			} else if value.Valid {
				_m.IsEnable = value.Bool
			}
		case envplugin.FieldExecutionOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field execution_order", values[i])
			} else if value.Valid {
				_m.ExecutionOrder = int32(value.Int64)
			}
		case envplugin.FieldConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value.Valid {
				_m.Config = new(string)
				*_m.Config = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EnvPlugin.
// This includes values selected through modifiers, order, etc.
func (_m *EnvPlugin) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEnv queries the "env" edge of the EnvPlugin entity.
func (_m *EnvPlugin) QueryEnv() *EnvQuery {
	return NewEnvPluginClient(_m.config).QueryEnv(_m)
}

// QueryPlugin queries the "plugin" edge of the EnvPlugin entity.
func (_m *EnvPlugin) QueryPlugin() *PluginQuery {
	return NewEnvPluginClient(_m.config).QueryPlugin(_m)
}

// Update returns a builder for updating this EnvPlugin.
// Note that you need to call EnvPlugin.Unwrap() before calling this method if this EnvPlugin
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EnvPlugin) Update() *EnvPluginUpdateOne {
	return NewEnvPluginClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EnvPlugin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EnvPlugin) Unwrap() *EnvPlugin {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EnvPlugin is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EnvPlugin) String() string {
	var builder strings.Builder
	builder.WriteString("EnvPlugin(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("env_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnvID))
	builder.WriteString(", ")
	builder.WriteString("plugin_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PluginID))
	builder.WriteString(", ")
	builder.WriteString("is_enable=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsEnable))
	builder.WriteString(", ")
	builder.WriteString("execution_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExecutionOrder))
	builder.WriteString(", ")
	if v := _m.Config; v != nil {
		builder.WriteString("config=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// EnvPlugins is a parsable slice of EnvPlugin.
type EnvPlugins []*EnvPlugin
