// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/env"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/envplugin"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/plugin"
)

// EnvPluginCreate is the builder for creating a EnvPlugin entity.
type EnvPluginCreate struct {
	config
	mutation *EnvPluginMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnvPluginCreate) SetCreatedAt(v time.Time) *EnvPluginCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnvPluginCreate) SetNillableCreatedAt(v *time.Time) *EnvPluginCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnvPluginCreate) SetUpdatedAt(v time.Time) *EnvPluginCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnvPluginCreate) SetNillableUpdatedAt(v *time.Time) *EnvPluginCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEnvID sets the "env_id" field.
func (_c *EnvPluginCreate) SetEnvID(v int64) *EnvPluginCreate {
	_c.mutation.SetEnvID(v)
	return _c
}

// SetPluginID sets the "plugin_id" field.
func (_c *EnvPluginCreate) SetPluginID(v int64) *EnvPluginCreate {
	_c.mutation.SetPluginID(v)
	return _c
}

// SetIsEnable sets the "is_enable" field.
func (_c *EnvPluginCreate) SetIsEnable(v bool) *EnvPluginCreate {
	_c.mutation.SetIsEnable(v)
	return _c
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_c *EnvPluginCreate) SetNillableIsEnable(v *bool) *EnvPluginCreate {
	if v != nil {
		_c.SetIsEnable(*v)
	}
	return _c
}

// SetExecutionOrder sets the "execution_order" field.
func (_c *EnvPluginCreate) SetExecutionOrder(v int32) *EnvPluginCreate {
	_c.mutation.SetExecutionOrder(v)
	return _c
}

// SetNillableExecutionOrder sets the "execution_order" field if the given value is not nil.
func (_c *EnvPluginCreate) SetNillableExecutionOrder(v *int32) *EnvPluginCreate {
	if v != nil {
		_c.SetExecutionOrder(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *EnvPluginCreate) SetConfig(v string) *EnvPluginCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_c *EnvPluginCreate) SetNillableConfig(v *string) *EnvPluginCreate {
	if v != nil {
		_c.SetConfig(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EnvPluginCreate) SetID(v int64) *EnvPluginCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetEnv sets the "env" edge to the Env entity.
func (_c *EnvPluginCreate) SetEnv(v *Env) *EnvPluginCreate {
	return _c.SetEnvID(v.ID)
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_c *EnvPluginCreate) SetPlugin(v *Plugin) *EnvPluginCreate {
	return _c.SetPluginID(v.ID)
}

// Mutation returns the EnvPluginMutation object of the builder.
func (_c *EnvPluginCreate) Mutation() *EnvPluginMutation {
	return _c.mutation
}

// Save creates the EnvPlugin in the database.
func (_c *EnvPluginCreate) Save(ctx context.Context) (*EnvPlugin, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnvPluginCreate) SaveX(ctx context.Context) *EnvPlugin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnvPluginCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnvPluginCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnvPluginCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := envplugin.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := envplugin.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsEnable(); !ok {
		v := envplugin.DefaultIsEnable
		_c.mutation.SetIsEnable(v)
	}
	if _, ok := _c.mutation.ExecutionOrder(); !ok {
		v := envplugin.DefaultExecutionOrder
		_c.mutation.SetExecutionOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnvPluginCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EnvPlugin.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EnvPlugin.updated_at"`)}
	}
	if _, ok := _c.mutation.EnvID(); !ok {
		return &ValidationError{Name: "env_id", err: errors.New(`ent: missing required field "EnvPlugin.env_id"`)}
	}
	if _, ok := _c.mutation.PluginID(); !ok {
		return &ValidationError{Name: "plugin_id", err: errors.New(`ent: missing required field "EnvPlugin.plugin_id"`)}
	}
	if _, ok := _c.mutation.IsEnable(); !ok {
		return &ValidationError{Name: "is_enable", err: errors.New(`ent: missing required field "EnvPlugin.is_enable"`)}
	}
	if _, ok := _c.mutation.ExecutionOrder(); !ok {
		return &ValidationError{Name: "execution_order", err: errors.New(`ent: missing required field "EnvPlugin.execution_order"`)}
	}
	if len(_c.mutation.EnvIDs()) == 0 {
		return &ValidationError{Name: "env", err: errors.New(`ent: missing required edge "EnvPlugin.env"`)}
	}
	if len(_c.mutation.PluginIDs()) == 0 {
		return &ValidationError{Name: "plugin", err: errors.New(`ent: missing required edge "EnvPlugin.plugin"`)}
	}
	return nil
}

func (_c *EnvPluginCreate) sqlSave(ctx context.Context) (*EnvPlugin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnvPluginCreate) createSpec() (*EnvPlugin, *sqlgraph.CreateSpec) {
	var (
		_node = &EnvPlugin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(envplugin.Table, sqlgraph.NewFieldSpec(envplugin.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(envplugin.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(envplugin.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.IsEnable(); ok {
		_spec.SetField(envplugin.FieldIsEnable, field.TypeBool, value)
		_node.IsEnable = value
	}
	if value, ok := _c.mutation.ExecutionOrder(); ok {
		_spec.SetField(envplugin.FieldExecutionOrder, field.TypeInt32, value)
		_node.ExecutionOrder = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(envplugin.FieldConfig, field.TypeString, value)
		_node.Config = &value
	}
	if nodes := _c.mutation.EnvIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envplugin.EnvTable,
			Columns: []string{envplugin.EnvColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(env.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EnvID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envplugin.PluginTable,
			Columns: []string{envplugin.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PluginID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EnvPluginCreateBulk is the builder for creating many EnvPlugin entities in bulk.
type EnvPluginCreateBulk struct {
	config
	err      error
	builders []*EnvPluginCreate
}

// Save creates the EnvPlugin entities in the database.
func (_c *EnvPluginCreateBulk) Save(ctx context.Context) ([]*EnvPlugin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnvPlugin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnvPluginMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnvPluginCreateBulk) SaveX(ctx context.Context) []*EnvPlugin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnvPluginCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnvPluginCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
