// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/loginhistory"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/predicate"
)

// LoginHistoryUpdate is the builder for updating LoginHistory entities.
type LoginHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *LoginHistoryMutation
}

// Where appends a list predicates to the LoginHistoryUpdate builder.
func (_u *LoginHistoryUpdate) Where(ps ...predicate.LoginHistory) *LoginHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LoginHistoryUpdate) SetUpdatedAt(v time.Time) *LoginHistoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIP sets the "ip" field.
func (_u *LoginHistoryUpdate) SetIP(v string) *LoginHistoryUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *LoginHistoryUpdate) SetNillableIP(v *string) *LoginHistoryUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *LoginHistoryUpdate) SetAddress(v string) *LoginHistoryUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *LoginHistoryUpdate) SetNillableAddress(v *string) *LoginHistoryUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *LoginHistoryUpdate) ClearAddress() *LoginHistoryUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// SetState sets the "state" field.
func (_u *LoginHistoryUpdate) SetState(v bool) *LoginHistoryUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *LoginHistoryUpdate) SetNillableState(v *bool) *LoginHistoryUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// Mutation returns the LoginHistoryMutation object of the builder.
func (_u *LoginHistoryUpdate) Mutation() *LoginHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LoginHistoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LoginHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LoginHistoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := loginhistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoginHistoryUpdate) check() error {
	if v, ok := _u.mutation.IP(); ok {
		if err := loginhistory.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "LoginHistory.ip": %w`, err)}
		}
	}
	return nil
}

func (_u *LoginHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loginhistory.Table, loginhistory.Columns, sqlgraph.NewFieldSpec(loginhistory.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(loginhistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(loginhistory.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(loginhistory.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(loginhistory.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(loginhistory.FieldState, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LoginHistoryUpdateOne is the builder for updating a single LoginHistory entity.
type LoginHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoginHistoryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LoginHistoryUpdateOne) SetUpdatedAt(v time.Time) *LoginHistoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIP sets the "ip" field.
func (_u *LoginHistoryUpdateOne) SetIP(v string) *LoginHistoryUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *LoginHistoryUpdateOne) SetNillableIP(v *string) *LoginHistoryUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *LoginHistoryUpdateOne) SetAddress(v string) *LoginHistoryUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *LoginHistoryUpdateOne) SetNillableAddress(v *string) *LoginHistoryUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *LoginHistoryUpdateOne) ClearAddress() *LoginHistoryUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// SetState sets the "state" field.
func (_u *LoginHistoryUpdateOne) SetState(v bool) *LoginHistoryUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *LoginHistoryUpdateOne) SetNillableState(v *bool) *LoginHistoryUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// Mutation returns the LoginHistoryMutation object of the builder.
func (_u *LoginHistoryUpdateOne) Mutation() *LoginHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the LoginHistoryUpdate builder.
func (_u *LoginHistoryUpdateOne) Where(ps ...predicate.LoginHistory) *LoginHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LoginHistoryUpdateOne) Select(field string, fields ...string) *LoginHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LoginHistory entity.
func (_u *LoginHistoryUpdateOne) Save(ctx context.Context) (*LoginHistory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginHistoryUpdateOne) SaveX(ctx context.Context) *LoginHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LoginHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LoginHistoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := loginhistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoginHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.IP(); ok {
		if err := loginhistory.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "LoginHistory.ip": %w`, err)}
		}
	}
	return nil
}

func (_u *LoginHistoryUpdateOne) sqlSave(ctx context.Context) (_node *LoginHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loginhistory.Table, loginhistory.Columns, sqlgraph.NewFieldSpec(loginhistory.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LoginHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginhistory.FieldID)
		for _, f := range fields {
			if !loginhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loginhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(loginhistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(loginhistory.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(loginhistory.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(loginhistory.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(loginhistory.FieldState, field.TypeBool, value)
	}
	_node = &LoginHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
