// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/plugin"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/pluginexecutionlog"
)

// PluginExecutionLogCreate is the builder for creating a PluginExecutionLog entity.
type PluginExecutionLogCreate struct {
	config
	mutation *PluginExecutionLogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PluginExecutionLogCreate) SetCreatedAt(v time.Time) *PluginExecutionLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PluginExecutionLogCreate) SetNillableCreatedAt(v *time.Time) *PluginExecutionLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPluginID sets the "plugin_id" field.
func (_c *PluginExecutionLogCreate) SetPluginID(v int64) *PluginExecutionLogCreate {
	_c.mutation.SetPluginID(v)
	return _c
}

// SetEnvID sets the "env_id" field.
func (_c *PluginExecutionLogCreate) SetEnvID(v int64) *PluginExecutionLogCreate {
	_c.mutation.SetEnvID(v)
	return _c
}

// SetExecutionStatus sets the "execution_status" field.
func (_c *PluginExecutionLogCreate) SetExecutionStatus(v string) *PluginExecutionLogCreate {
	_c.mutation.SetExecutionStatus(v)
	return _c
}

// SetExecutionTime sets the "execution_time" field.
func (_c *PluginExecutionLogCreate) SetExecutionTime(v int32) *PluginExecutionLogCreate {
	_c.mutation.SetExecutionTime(v)
	return _c
}

// SetInputData sets the "input_data" field.
func (_c *PluginExecutionLogCreate) SetInputData(v string) *PluginExecutionLogCreate {
	_c.mutation.SetInputData(v)
	return _c
}

// SetNillableInputData sets the "input_data" field if the given value is not nil.
func (_c *PluginExecutionLogCreate) SetNillableInputData(v *string) *PluginExecutionLogCreate {
	if v != nil {
		_c.SetInputData(*v)
	}
	return _c
}

// SetOutputData sets the "output_data" field.
func (_c *PluginExecutionLogCreate) SetOutputData(v string) *PluginExecutionLogCreate {
	_c.mutation.SetOutputData(v)
	return _c
}

// SetNillableOutputData sets the "output_data" field if the given value is not nil.
func (_c *PluginExecutionLogCreate) SetNillableOutputData(v *string) *PluginExecutionLogCreate {
	if v != nil {
		_c.SetOutputData(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *PluginExecutionLogCreate) SetErrorMessage(v string) *PluginExecutionLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *PluginExecutionLogCreate) SetNillableErrorMessage(v *string) *PluginExecutionLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetStackTrace sets the "stack_trace" field.
func (_c *PluginExecutionLogCreate) SetStackTrace(v string) *PluginExecutionLogCreate {
	_c.mutation.SetStackTrace(v)
	return _c
}

// SetNillableStackTrace sets the "stack_trace" field if the given value is not nil.
func (_c *PluginExecutionLogCreate) SetNillableStackTrace(v *string) *PluginExecutionLogCreate {
	if v != nil {
		_c.SetStackTrace(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PluginExecutionLogCreate) SetID(v int64) *PluginExecutionLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_c *PluginExecutionLogCreate) SetPlugin(v *Plugin) *PluginExecutionLogCreate {
	return _c.SetPluginID(v.ID)
}

// Mutation returns the PluginExecutionLogMutation object of the builder.
func (_c *PluginExecutionLogCreate) Mutation() *PluginExecutionLogMutation {
	return _c.mutation
}

// Save creates the PluginExecutionLog in the database.
func (_c *PluginExecutionLogCreate) Save(ctx context.Context) (*PluginExecutionLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginExecutionLogCreate) SaveX(ctx context.Context) *PluginExecutionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginExecutionLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginExecutionLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginExecutionLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pluginexecutionlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginExecutionLogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PluginExecutionLog.created_at"`)}
	}
	if _, ok := _c.mutation.PluginID(); !ok {
		return &ValidationError{Name: "plugin_id", err: errors.New(`ent: missing required field "PluginExecutionLog.plugin_id"`)}
	}
	if _, ok := _c.mutation.EnvID(); !ok {
		return &ValidationError{Name: "env_id", err: errors.New(`ent: missing required field "PluginExecutionLog.env_id"`)}
	}
	if _, ok := _c.mutation.ExecutionStatus(); !ok {
		return &ValidationError{Name: "execution_status", err: errors.New(`ent: missing required field "PluginExecutionLog.execution_status"`)}
	}
	if _, ok := _c.mutation.ExecutionTime(); !ok {
		return &ValidationError{Name: "execution_time", err: errors.New(`ent: missing required field "PluginExecutionLog.execution_time"`)}
	}
	if len(_c.mutation.PluginIDs()) == 0 {
		return &ValidationError{Name: "plugin", err: errors.New(`ent: missing required edge "PluginExecutionLog.plugin"`)}
	}
	return nil
}

func (_c *PluginExecutionLogCreate) sqlSave(ctx context.Context) (*PluginExecutionLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginExecutionLogCreate) createSpec() (*PluginExecutionLog, *sqlgraph.CreateSpec) {
	var (
		_node = &PluginExecutionLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pluginexecutionlog.Table, sqlgraph.NewFieldSpec(pluginexecutionlog.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pluginexecutionlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.EnvID(); ok {
		_spec.SetField(pluginexecutionlog.FieldEnvID, field.TypeInt64, value)
		_node.EnvID = value
	}
	if value, ok := _c.mutation.ExecutionStatus(); ok {
		_spec.SetField(pluginexecutionlog.FieldExecutionStatus, field.TypeString, value)
		_node.ExecutionStatus = value
	}
	if value, ok := _c.mutation.ExecutionTime(); ok {
		_spec.SetField(pluginexecutionlog.FieldExecutionTime, field.TypeInt32, value)
		_node.ExecutionTime = value
	}
	if value, ok := _c.mutation.InputData(); ok {
		_spec.SetField(pluginexecutionlog.FieldInputData, field.TypeString, value)
		_node.InputData = &value
	}
	if value, ok := _c.mutation.OutputData(); ok {
		_spec.SetField(pluginexecutionlog.FieldOutputData, field.TypeString, value)
		_node.OutputData = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(pluginexecutionlog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.StackTrace(); ok {
		_spec.SetField(pluginexecutionlog.FieldStackTrace, field.TypeString, value)
		_node.StackTrace = &value
	}
	if nodes := _c.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginexecutionlog.PluginTable,
			Columns: []string{pluginexecutionlog.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PluginID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PluginExecutionLogCreateBulk is the builder for creating many PluginExecutionLog entities in bulk.
type PluginExecutionLogCreateBulk struct {
	config
	err      error
	builders []*PluginExecutionLogCreate
}

// Save creates the PluginExecutionLog entities in the database.
func (_c *PluginExecutionLogCreateBulk) Save(ctx context.Context) ([]*PluginExecutionLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PluginExecutionLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginExecutionLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginExecutionLogCreateBulk) SaveX(ctx context.Context) []*PluginExecutionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginExecutionLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginExecutionLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
