// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/envplugin"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/plugin"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/pluginexecutionlog"
)

// PluginCreate is the builder for creating a Plugin entity.
type PluginCreate struct {
	config
	mutation *PluginMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PluginCreate) SetCreatedAt(v time.Time) *PluginCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PluginCreate) SetNillableCreatedAt(v *time.Time) *PluginCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PluginCreate) SetUpdatedAt(v time.Time) *PluginCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PluginCreate) SetNillableUpdatedAt(v *time.Time) *PluginCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PluginCreate) SetName(v string) *PluginCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PluginCreate) SetDescription(v string) *PluginCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PluginCreate) SetNillableDescription(v *string) *PluginCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *PluginCreate) SetVersion(v string) *PluginCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *PluginCreate) SetNillableVersion(v *string) *PluginCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetAuthor sets the "author" field.
func (_c *PluginCreate) SetAuthor(v string) *PluginCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_c *PluginCreate) SetNillableAuthor(v *string) *PluginCreate {
	if v != nil {
		_c.SetAuthor(*v)
	}
	return _c
}

// SetScriptContent sets the "script_content" field.
func (_c *PluginCreate) SetScriptContent(v string) *PluginCreate {
	_c.mutation.SetScriptContent(v)
	return _c
}

// SetIsEnable sets the "is_enable" field.
func (_c *PluginCreate) SetIsEnable(v bool) *PluginCreate {
	_c.mutation.SetIsEnable(v)
	return _c
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_c *PluginCreate) SetNillableIsEnable(v *bool) *PluginCreate {
	if v != nil {
		_c.SetIsEnable(*v)
	}
	return _c
}

// SetExecutionTimeout sets the "execution_timeout" field.
func (_c *PluginCreate) SetExecutionTimeout(v int32) *PluginCreate {
	_c.mutation.SetExecutionTimeout(v)
	return _c
}

// SetNillableExecutionTimeout sets the "execution_timeout" field if the given value is not nil.
func (_c *PluginCreate) SetNillableExecutionTimeout(v *int32) *PluginCreate {
	if v != nil {
		_c.SetExecutionTimeout(*v)
	}
	return _c
}

// SetTriggerEvent sets the "trigger_event" field.
func (_c *PluginCreate) SetTriggerEvent(v string) *PluginCreate {
	_c.mutation.SetTriggerEvent(v)
	return _c
}

// SetNillableTriggerEvent sets the "trigger_event" field if the given value is not nil.
func (_c *PluginCreate) SetNillableTriggerEvent(v *string) *PluginCreate {
	if v != nil {
		_c.SetTriggerEvent(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *PluginCreate) SetPriority(v int32) *PluginCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *PluginCreate) SetNillablePriority(v *int32) *PluginCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PluginCreate) SetID(v int64) *PluginCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddEnvPluginIDs adds the "env_plugins" edge to the EnvPlugin entity by IDs.
func (_c *PluginCreate) AddEnvPluginIDs(ids ...int64) *PluginCreate {
	_c.mutation.AddEnvPluginIDs(ids...)
	return _c
}

// AddEnvPlugins adds the "env_plugins" edges to the EnvPlugin entity.
func (_c *PluginCreate) AddEnvPlugins(v ...*EnvPlugin) *PluginCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEnvPluginIDs(ids...)
}

// AddExecutionLogIDs adds the "execution_logs" edge to the PluginExecutionLog entity by IDs.
func (_c *PluginCreate) AddExecutionLogIDs(ids ...int64) *PluginCreate {
	_c.mutation.AddExecutionLogIDs(ids...)
	return _c
}

// AddExecutionLogs adds the "execution_logs" edges to the PluginExecutionLog entity.
func (_c *PluginCreate) AddExecutionLogs(v ...*PluginExecutionLog) *PluginCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExecutionLogIDs(ids...)
}

// Mutation returns the PluginMutation object of the builder.
func (_c *PluginCreate) Mutation() *PluginMutation {
	return _c.mutation
}

// Save creates the Plugin in the database.
func (_c *PluginCreate) Save(ctx context.Context) (*Plugin, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginCreate) SaveX(ctx context.Context) *Plugin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := plugin.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := plugin.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := plugin.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.IsEnable(); !ok {
		v := plugin.DefaultIsEnable
		_c.mutation.SetIsEnable(v)
	}
	if _, ok := _c.mutation.ExecutionTimeout(); !ok {
		v := plugin.DefaultExecutionTimeout
		_c.mutation.SetExecutionTimeout(v)
	}
	if _, ok := _c.mutation.TriggerEvent(); !ok {
		v := plugin.DefaultTriggerEvent
		_c.mutation.SetTriggerEvent(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := plugin.DefaultPriority
		_c.mutation.SetPriority(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Plugin.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Plugin.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Plugin.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := plugin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plugin.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Plugin.version"`)}
	}
	if _, ok := _c.mutation.ScriptContent(); !ok {
		return &ValidationError{Name: "script_content", err: errors.New(`ent: missing required field "Plugin.script_content"`)}
	}
	if v, ok := _c.mutation.ScriptContent(); ok {
		if err := plugin.ScriptContentValidator(v); err != nil {
			return &ValidationError{Name: "script_content", err: fmt.Errorf(`ent: validator failed for field "Plugin.script_content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsEnable(); !ok {
		return &ValidationError{Name: "is_enable", err: errors.New(`ent: missing required field "Plugin.is_enable"`)}
	}
	if _, ok := _c.mutation.ExecutionTimeout(); !ok {
		return &ValidationError{Name: "execution_timeout", err: errors.New(`ent: missing required field "Plugin.execution_timeout"`)}
	}
	if _, ok := _c.mutation.TriggerEvent(); !ok {
		return &ValidationError{Name: "trigger_event", err: errors.New(`ent: missing required field "Plugin.trigger_event"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Plugin.priority"`)}
	}
	return nil
}

func (_c *PluginCreate) sqlSave(ctx context.Context) (*Plugin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginCreate) createSpec() (*Plugin, *sqlgraph.CreateSpec) {
	var (
		_node = &Plugin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(plugin.Table, sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(plugin.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(plugin.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(plugin.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(plugin.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(plugin.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(plugin.FieldAuthor, field.TypeString, value)
		_node.Author = &value
	}
	if value, ok := _c.mutation.ScriptContent(); ok {
		_spec.SetField(plugin.FieldScriptContent, field.TypeString, value)
		_node.ScriptContent = value
	}
	if value, ok := _c.mutation.IsEnable(); ok {
		_spec.SetField(plugin.FieldIsEnable, field.TypeBool, value)
		_node.IsEnable = value
	}
	if value, ok := _c.mutation.ExecutionTimeout(); ok {
		_spec.SetField(plugin.FieldExecutionTimeout, field.TypeInt32, value)
		_node.ExecutionTimeout = value
	}
	if value, ok := _c.mutation.TriggerEvent(); ok {
		_spec.SetField(plugin.FieldTriggerEvent, field.TypeString, value)
		_node.TriggerEvent = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(plugin.FieldPriority, field.TypeInt32, value)
		_node.Priority = value
	}
	if nodes := _c.mutation.EnvPluginsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.EnvPluginsTable,
			Columns: []string{plugin.EnvPluginsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envplugin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExecutionLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.ExecutionLogsTable,
			Columns: []string{plugin.ExecutionLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginexecutionlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PluginCreateBulk is the builder for creating many Plugin entities in bulk.
type PluginCreateBulk struct {
	config
	err      error
	builders []*PluginCreate
}

// Save creates the Plugin entities in the database.
func (_c *PluginCreateBulk) Save(ctx context.Context) ([]*Plugin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Plugin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginCreateBulk) SaveX(ctx context.Context) []*Plugin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
