// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/plugin"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/pluginexecutionlog"
)

// PluginExecutionLog is the model entity for the PluginExecutionLog schema.
type PluginExecutionLog struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID int64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 插件ID
	PluginID int64 `json:"plugin_id,omitempty"`
	// 环境变量ID
	EnvID int64 `json:"env_id,omitempty"`
	// 执行状态(success,error,timeout)
	ExecutionStatus string `json:"execution_status,omitempty"`
	// 执行耗时(毫秒)
	ExecutionTime int32 `json:"execution_time,omitempty"`
	// 输入数据
	InputData *string `json:"input_data,omitempty"`
	// 输出数据
	OutputData *string `json:"output_data,omitempty"`
	// 错误信息
	ErrorMessage *string `json:"error_message,omitempty"`
	// 错误堆栈
	StackTrace *string `json:"stack_trace,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PluginExecutionLogQuery when eager-loading is set.
	Edges        PluginExecutionLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PluginExecutionLogEdges holds the relations/edges for other nodes in the graph.
type PluginExecutionLogEdges struct {
	// Plugin holds the value of the plugin edge.
	Plugin *Plugin `json:"plugin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PluginOrErr returns the Plugin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PluginExecutionLogEdges) PluginOrErr() (*Plugin, error) {
	if e.Plugin != nil {
		return e.Plugin, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: plugin.Label}
	}
	return nil, &NotLoadedError{edge: "plugin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PluginExecutionLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pluginexecutionlog.FieldID, pluginexecutionlog.FieldPluginID, pluginexecutionlog.FieldEnvID, pluginexecutionlog.FieldExecutionTime:
			values[i] = new(sql.NullInt64)
		case pluginexecutionlog.FieldExecutionStatus, pluginexecutionlog.FieldInputData, pluginexecutionlog.FieldOutputData, pluginexecutionlog.FieldErrorMessage, pluginexecutionlog.FieldStackTrace:
			values[i] = new(sql.NullString)
		case pluginexecutionlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PluginExecutionLog fields.
func (_m *PluginExecutionLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pluginexecutionlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case pluginexecutionlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pluginexecutionlog.FieldPluginID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plugin_id", values[i])
			} else if value.Valid {
				_m.PluginID = value.Int64
			}
		case pluginexecutionlog.FieldEnvID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field env_id", values[i])
			} else if value.Valid {
				_m.EnvID = value.Int64
			}
		case pluginexecutionlog.FieldExecutionStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_status", values[i])
			} else if value.Valid {
				_m.ExecutionStatus = value.String
			}
		case pluginexecutionlog.FieldExecutionTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field execution_time", values[i])
			} else if value.Valid {
				_m.ExecutionTime = int32(value.Int64)
			}
		case pluginexecutionlog.FieldInputData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field input_data", values[i])
			} else if value.Valid {
				_m.InputData = new(string)
				*_m.InputData = value.String
			}
		case pluginexecutionlog.FieldOutputData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field output_data", values[i])
			} else if value.Valid {
				_m.OutputData = new(string)
				*_m.OutputData = value.String
			}
		case pluginexecutionlog.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case pluginexecutionlog.FieldStackTrace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stack_trace", values[i])
			} else if value.Valid {
				_m.StackTrace = new(string)
				*_m.StackTrace = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PluginExecutionLog.
// This includes values selected through modifiers, order, etc.
func (_m *PluginExecutionLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlugin queries the "plugin" edge of the PluginExecutionLog entity.
func (_m *PluginExecutionLog) QueryPlugin() *PluginQuery {
	return NewPluginExecutionLogClient(_m.config).QueryPlugin(_m)
}

// Update returns a builder for updating this PluginExecutionLog.
// Note that you need to call PluginExecutionLog.Unwrap() before calling this method if this PluginExecutionLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PluginExecutionLog) Update() *PluginExecutionLogUpdateOne {
	return NewPluginExecutionLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PluginExecutionLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PluginExecutionLog) Unwrap() *PluginExecutionLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PluginExecutionLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PluginExecutionLog) String() string {
	var builder strings.Builder
	builder.WriteString("PluginExecutionLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("plugin_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PluginID))
	builder.WriteString(", ")
	builder.WriteString("env_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnvID))
	builder.WriteString(", ")
	builder.WriteString("execution_status=")
	builder.WriteString(_m.ExecutionStatus)
	builder.WriteString(", ")
	builder.WriteString("execution_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExecutionTime))
	builder.WriteString(", ")
	if v := _m.InputData; v != nil {
		builder.WriteString("input_data=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OutputData; v != nil {
		builder.WriteString("output_data=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.StackTrace; v != nil {
		builder.WriteString("stack_trace=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// PluginExecutionLogs is a parsable slice of PluginExecutionLog.
type PluginExecutionLogs []*PluginExecutionLog
