// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/plugin"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/pluginexecutionlog"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/predicate"
)

// PluginExecutionLogUpdate is the builder for updating PluginExecutionLog entities.
type PluginExecutionLogUpdate struct {
	config
	hooks    []Hook
	mutation *PluginExecutionLogMutation
}

// Where appends a list predicates to the PluginExecutionLogUpdate builder.
func (_u *PluginExecutionLogUpdate) Where(ps ...predicate.PluginExecutionLog) *PluginExecutionLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *PluginExecutionLogUpdate) SetPluginID(v int64) *PluginExecutionLogUpdate {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *PluginExecutionLogUpdate) SetNillablePluginID(v *int64) *PluginExecutionLogUpdate {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetEnvID sets the "env_id" field.
func (_u *PluginExecutionLogUpdate) SetEnvID(v int64) *PluginExecutionLogUpdate {
	_u.mutation.ResetEnvID()
	_u.mutation.SetEnvID(v)
	return _u
}

// SetNillableEnvID sets the "env_id" field if the given value is not nil.
func (_u *PluginExecutionLogUpdate) SetNillableEnvID(v *int64) *PluginExecutionLogUpdate {
	if v != nil {
		_u.SetEnvID(*v)
	}
	return _u
}

// AddEnvID adds value to the "env_id" field.
func (_u *PluginExecutionLogUpdate) AddEnvID(v int64) *PluginExecutionLogUpdate {
	_u.mutation.AddEnvID(v)
	return _u
}

// SetExecutionStatus sets the "execution_status" field.
func (_u *PluginExecutionLogUpdate) SetExecutionStatus(v string) *PluginExecutionLogUpdate {
	_u.mutation.SetExecutionStatus(v)
	return _u
}

// SetNillableExecutionStatus sets the "execution_status" field if the given value is not nil.
func (_u *PluginExecutionLogUpdate) SetNillableExecutionStatus(v *string) *PluginExecutionLogUpdate {
	if v != nil {
		_u.SetExecutionStatus(*v)
	}
	return _u
}

// SetExecutionTime sets the "execution_time" field.
func (_u *PluginExecutionLogUpdate) SetExecutionTime(v int32) *PluginExecutionLogUpdate {
	_u.mutation.ResetExecutionTime()
	_u.mutation.SetExecutionTime(v)
	return _u
}

// SetNillableExecutionTime sets the "execution_time" field if the given value is not nil.
func (_u *PluginExecutionLogUpdate) SetNillableExecutionTime(v *int32) *PluginExecutionLogUpdate {
	if v != nil {
		_u.SetExecutionTime(*v)
	}
	return _u
}

// AddExecutionTime adds value to the "execution_time" field.
func (_u *PluginExecutionLogUpdate) AddExecutionTime(v int32) *PluginExecutionLogUpdate {
	_u.mutation.AddExecutionTime(v)
	return _u
}

// SetInputData sets the "input_data" field.
func (_u *PluginExecutionLogUpdate) SetInputData(v string) *PluginExecutionLogUpdate {
	_u.mutation.SetInputData(v)
	return _u
}

// SetNillableInputData sets the "input_data" field if the given value is not nil.
func (_u *PluginExecutionLogUpdate) SetNillableInputData(v *string) *PluginExecutionLogUpdate {
	if v != nil {
		_u.SetInputData(*v)
	}
	return _u
}

// ClearInputData clears the value of the "input_data" field.
func (_u *PluginExecutionLogUpdate) ClearInputData() *PluginExecutionLogUpdate {
	_u.mutation.ClearInputData()
	return _u
}

// SetOutputData sets the "output_data" field.
func (_u *PluginExecutionLogUpdate) SetOutputData(v string) *PluginExecutionLogUpdate {
	_u.mutation.SetOutputData(v)
	return _u
}

// SetNillableOutputData sets the "output_data" field if the given value is not nil.
func (_u *PluginExecutionLogUpdate) SetNillableOutputData(v *string) *PluginExecutionLogUpdate {
	if v != nil {
		_u.SetOutputData(*v)
	}
	return _u
}

// ClearOutputData clears the value of the "output_data" field.
func (_u *PluginExecutionLogUpdate) ClearOutputData() *PluginExecutionLogUpdate {
	_u.mutation.ClearOutputData()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *PluginExecutionLogUpdate) SetErrorMessage(v string) *PluginExecutionLogUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *PluginExecutionLogUpdate) SetNillableErrorMessage(v *string) *PluginExecutionLogUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *PluginExecutionLogUpdate) ClearErrorMessage() *PluginExecutionLogUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStackTrace sets the "stack_trace" field.
func (_u *PluginExecutionLogUpdate) SetStackTrace(v string) *PluginExecutionLogUpdate {
	_u.mutation.SetStackTrace(v)
	return _u
}

// SetNillableStackTrace sets the "stack_trace" field if the given value is not nil.
func (_u *PluginExecutionLogUpdate) SetNillableStackTrace(v *string) *PluginExecutionLogUpdate {
	if v != nil {
		_u.SetStackTrace(*v)
	}
	return _u
}

// ClearStackTrace clears the value of the "stack_trace" field.
func (_u *PluginExecutionLogUpdate) ClearStackTrace() *PluginExecutionLogUpdate {
	_u.mutation.ClearStackTrace()
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *PluginExecutionLogUpdate) SetPlugin(v *Plugin) *PluginExecutionLogUpdate {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the PluginExecutionLogMutation object of the builder.
func (_u *PluginExecutionLogUpdate) Mutation() *PluginExecutionLogMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *PluginExecutionLogUpdate) ClearPlugin() *PluginExecutionLogUpdate {
	_u.mutation.ClearPlugin()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PluginExecutionLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginExecutionLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PluginExecutionLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginExecutionLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginExecutionLogUpdate) check() error {
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PluginExecutionLog.plugin"`)
	}
	return nil
}

func (_u *PluginExecutionLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginexecutionlog.Table, pluginexecutionlog.Columns, sqlgraph.NewFieldSpec(pluginexecutionlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EnvID(); ok {
		_spec.SetField(pluginexecutionlog.FieldEnvID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEnvID(); ok {
		_spec.AddField(pluginexecutionlog.FieldEnvID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExecutionStatus(); ok {
		_spec.SetField(pluginexecutionlog.FieldExecutionStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutionTime(); ok {
		_spec.SetField(pluginexecutionlog.FieldExecutionTime, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedExecutionTime(); ok {
		_spec.AddField(pluginexecutionlog.FieldExecutionTime, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.InputData(); ok {
		_spec.SetField(pluginexecutionlog.FieldInputData, field.TypeString, value)
	}
	if _u.mutation.InputDataCleared() {
		_spec.ClearField(pluginexecutionlog.FieldInputData, field.TypeString)
	}
	if value, ok := _u.mutation.OutputData(); ok {
		_spec.SetField(pluginexecutionlog.FieldOutputData, field.TypeString, value)
	}
	if _u.mutation.OutputDataCleared() {
		_spec.ClearField(pluginexecutionlog.FieldOutputData, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(pluginexecutionlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(pluginexecutionlog.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StackTrace(); ok {
		_spec.SetField(pluginexecutionlog.FieldStackTrace, field.TypeString, value)
	}
	if _u.mutation.StackTraceCleared() {
		_spec.ClearField(pluginexecutionlog.FieldStackTrace, field.TypeString)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginexecutionlog.PluginTable,
			Columns: []string{pluginexecutionlog.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginexecutionlog.PluginTable,
			Columns: []string{pluginexecutionlog.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginexecutionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PluginExecutionLogUpdateOne is the builder for updating a single PluginExecutionLog entity.
type PluginExecutionLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginExecutionLogMutation
}

// SetPluginID sets the "plugin_id" field.
func (_u *PluginExecutionLogUpdateOne) SetPluginID(v int64) *PluginExecutionLogUpdateOne {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *PluginExecutionLogUpdateOne) SetNillablePluginID(v *int64) *PluginExecutionLogUpdateOne {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetEnvID sets the "env_id" field.
func (_u *PluginExecutionLogUpdateOne) SetEnvID(v int64) *PluginExecutionLogUpdateOne {
	_u.mutation.ResetEnvID()
	_u.mutation.SetEnvID(v)
	return _u
}

// SetNillableEnvID sets the "env_id" field if the given value is not nil.
func (_u *PluginExecutionLogUpdateOne) SetNillableEnvID(v *int64) *PluginExecutionLogUpdateOne {
	if v != nil {
		_u.SetEnvID(*v)
	}
	return _u
}

// AddEnvID adds value to the "env_id" field.
func (_u *PluginExecutionLogUpdateOne) AddEnvID(v int64) *PluginExecutionLogUpdateOne {
	_u.mutation.AddEnvID(v)
	return _u
}

// SetExecutionStatus sets the "execution_status" field.
func (_u *PluginExecutionLogUpdateOne) SetExecutionStatus(v string) *PluginExecutionLogUpdateOne {
	_u.mutation.SetExecutionStatus(v)
	return _u
}

// SetNillableExecutionStatus sets the "execution_status" field if the given value is not nil.
func (_u *PluginExecutionLogUpdateOne) SetNillableExecutionStatus(v *string) *PluginExecutionLogUpdateOne {
	if v != nil {
		_u.SetExecutionStatus(*v)
	}
	return _u
}

// SetExecutionTime sets the "execution_time" field.
func (_u *PluginExecutionLogUpdateOne) SetExecutionTime(v int32) *PluginExecutionLogUpdateOne {
	_u.mutation.ResetExecutionTime()
	_u.mutation.SetExecutionTime(v)
	return _u
}

// SetNillableExecutionTime sets the "execution_time" field if the given value is not nil.
func (_u *PluginExecutionLogUpdateOne) SetNillableExecutionTime(v *int32) *PluginExecutionLogUpdateOne {
	if v != nil {
		_u.SetExecutionTime(*v)
	}
	return _u
}

// AddExecutionTime adds value to the "execution_time" field.
func (_u *PluginExecutionLogUpdateOne) AddExecutionTime(v int32) *PluginExecutionLogUpdateOne {
	_u.mutation.AddExecutionTime(v)
	return _u
}

// SetInputData sets the "input_data" field.
func (_u *PluginExecutionLogUpdateOne) SetInputData(v string) *PluginExecutionLogUpdateOne {
	_u.mutation.SetInputData(v)
	return _u
}

// SetNillableInputData sets the "input_data" field if the given value is not nil.
func (_u *PluginExecutionLogUpdateOne) SetNillableInputData(v *string) *PluginExecutionLogUpdateOne {
	if v != nil {
		_u.SetInputData(*v)
	}
	return _u
}

// ClearInputData clears the value of the "input_data" field.
func (_u *PluginExecutionLogUpdateOne) ClearInputData() *PluginExecutionLogUpdateOne {
	_u.mutation.ClearInputData()
	return _u
}

// SetOutputData sets the "output_data" field.
func (_u *PluginExecutionLogUpdateOne) SetOutputData(v string) *PluginExecutionLogUpdateOne {
	_u.mutation.SetOutputData(v)
	return _u
}

// SetNillableOutputData sets the "output_data" field if the given value is not nil.
func (_u *PluginExecutionLogUpdateOne) SetNillableOutputData(v *string) *PluginExecutionLogUpdateOne {
	if v != nil {
		_u.SetOutputData(*v)
	}
	return _u
}

// ClearOutputData clears the value of the "output_data" field.
func (_u *PluginExecutionLogUpdateOne) ClearOutputData() *PluginExecutionLogUpdateOne {
	_u.mutation.ClearOutputData()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *PluginExecutionLogUpdateOne) SetErrorMessage(v string) *PluginExecutionLogUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *PluginExecutionLogUpdateOne) SetNillableErrorMessage(v *string) *PluginExecutionLogUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *PluginExecutionLogUpdateOne) ClearErrorMessage() *PluginExecutionLogUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStackTrace sets the "stack_trace" field.
func (_u *PluginExecutionLogUpdateOne) SetStackTrace(v string) *PluginExecutionLogUpdateOne {
	_u.mutation.SetStackTrace(v)
	return _u
}

// SetNillableStackTrace sets the "stack_trace" field if the given value is not nil.
func (_u *PluginExecutionLogUpdateOne) SetNillableStackTrace(v *string) *PluginExecutionLogUpdateOne {
	if v != nil {
		_u.SetStackTrace(*v)
	}
	return _u
}

// ClearStackTrace clears the value of the "stack_trace" field.
func (_u *PluginExecutionLogUpdateOne) ClearStackTrace() *PluginExecutionLogUpdateOne {
	_u.mutation.ClearStackTrace()
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *PluginExecutionLogUpdateOne) SetPlugin(v *Plugin) *PluginExecutionLogUpdateOne {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the PluginExecutionLogMutation object of the builder.
func (_u *PluginExecutionLogUpdateOne) Mutation() *PluginExecutionLogMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *PluginExecutionLogUpdateOne) ClearPlugin() *PluginExecutionLogUpdateOne {
	_u.mutation.ClearPlugin()
	return _u
}

// Where appends a list predicates to the PluginExecutionLogUpdate builder.
func (_u *PluginExecutionLogUpdateOne) Where(ps ...predicate.PluginExecutionLog) *PluginExecutionLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PluginExecutionLogUpdateOne) Select(field string, fields ...string) *PluginExecutionLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PluginExecutionLog entity.
func (_u *PluginExecutionLogUpdateOne) Save(ctx context.Context) (*PluginExecutionLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginExecutionLogUpdateOne) SaveX(ctx context.Context) *PluginExecutionLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PluginExecutionLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginExecutionLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginExecutionLogUpdateOne) check() error {
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PluginExecutionLog.plugin"`)
	}
	return nil
}

func (_u *PluginExecutionLogUpdateOne) sqlSave(ctx context.Context) (_node *PluginExecutionLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginexecutionlog.Table, pluginexecutionlog.Columns, sqlgraph.NewFieldSpec(pluginexecutionlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PluginExecutionLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pluginexecutionlog.FieldID)
		for _, f := range fields {
			if !pluginexecutionlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pluginexecutionlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EnvID(); ok {
		_spec.SetField(pluginexecutionlog.FieldEnvID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEnvID(); ok {
		_spec.AddField(pluginexecutionlog.FieldEnvID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExecutionStatus(); ok {
		_spec.SetField(pluginexecutionlog.FieldExecutionStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutionTime(); ok {
		_spec.SetField(pluginexecutionlog.FieldExecutionTime, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedExecutionTime(); ok {
		_spec.AddField(pluginexecutionlog.FieldExecutionTime, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.InputData(); ok {
		_spec.SetField(pluginexecutionlog.FieldInputData, field.TypeString, value)
	}
	if _u.mutation.InputDataCleared() {
		_spec.ClearField(pluginexecutionlog.FieldInputData, field.TypeString)
	}
	if value, ok := _u.mutation.OutputData(); ok {
		_spec.SetField(pluginexecutionlog.FieldOutputData, field.TypeString, value)
	}
	if _u.mutation.OutputDataCleared() {
		_spec.ClearField(pluginexecutionlog.FieldOutputData, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(pluginexecutionlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(pluginexecutionlog.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StackTrace(); ok {
		_spec.SetField(pluginexecutionlog.FieldStackTrace, field.TypeString, value)
	}
	if _u.mutation.StackTraceCleared() {
		_spec.ClearField(pluginexecutionlog.FieldStackTrace, field.TypeString)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginexecutionlog.PluginTable,
			Columns: []string{pluginexecutionlog.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginexecutionlog.PluginTable,
			Columns: []string{pluginexecutionlog.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PluginExecutionLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginexecutionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
