// Code generated by ent, DO NOT EDIT.

package env

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the env type in the database.
	Label = "env"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRemarks holds the string denoting the remarks field in the database.
	FieldRemarks = "remarks"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldRegex holds the string denoting the regex field in the database.
	FieldRegex = "regex"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldRegexUpdate holds the string denoting the regex_update field in the database.
	FieldRegexUpdate = "regex_update"
	// FieldIsAutoEnvEnable holds the string denoting the is_auto_env_enable field in the database.
	FieldIsAutoEnvEnable = "is_auto_env_enable"
	// FieldEnableKey holds the string denoting the enable_key field in the database.
	FieldEnableKey = "enable_key"
	// FieldCdkLimit holds the string denoting the cdk_limit field in the database.
	FieldCdkLimit = "cdk_limit"
	// FieldIsPrompt holds the string denoting the is_prompt field in the database.
	FieldIsPrompt = "is_prompt"
	// FieldPromptLevel holds the string denoting the prompt_level field in the database.
	FieldPromptLevel = "prompt_level"
	// FieldPromptContent holds the string denoting the prompt_content field in the database.
	FieldPromptContent = "prompt_content"
	// FieldIsEnable holds the string denoting the is_enable field in the database.
	FieldIsEnable = "is_enable"
	// EdgePanels holds the string denoting the panels edge name in mutations.
	EdgePanels = "panels"
	// EdgeEnvPlugins holds the string denoting the env_plugins edge name in mutations.
	EdgeEnvPlugins = "env_plugins"
	// Table holds the table name of the env in the database.
	Table = "envs"
	// PanelsTable is the table that holds the panels relation/edge. The primary key declared below.
	PanelsTable = "env_panels"
	// PanelsInverseTable is the table name for the Panel entity.
	// It exists in this package in order to avoid circular dependency with the "panel" package.
	PanelsInverseTable = "panels"
	// EnvPluginsTable is the table that holds the env_plugins relation/edge.
	EnvPluginsTable = "env_plugins"
	// EnvPluginsInverseTable is the table name for the EnvPlugin entity.
	// It exists in this package in order to avoid circular dependency with the "envplugin" package.
	EnvPluginsInverseTable = "env_plugins"
	// EnvPluginsColumn is the table column denoting the env_plugins relation/edge.
	EnvPluginsColumn = "env_id"
)

// Columns holds all SQL columns for env fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldRemarks,
	FieldQuantity,
	FieldRegex,
	FieldMode,
	FieldRegexUpdate,
	FieldIsAutoEnvEnable,
	FieldEnableKey,
	FieldCdkLimit,
	FieldIsPrompt,
	FieldPromptLevel,
	FieldPromptContent,
	FieldIsEnable,
}

var (
	// PanelsPrimaryKey and PanelsColumn2 are the table columns denoting the
	// primary key for the panels relation (M2M).
	PanelsPrimaryKey = []string{"env_id", "panel_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultIsAutoEnvEnable holds the default value on creation for the "is_auto_env_enable" field.
	DefaultIsAutoEnvEnable bool
	// DefaultCdkLimit holds the default value on creation for the "cdk_limit" field.
	DefaultCdkLimit int32
)

// OrderOption defines the ordering options for the Env queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByRemarks orders the results by the remarks field.
func ByRemarks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemarks, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByRegex orders the results by the regex field.
func ByRegex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegex, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByRegexUpdate orders the results by the regex_update field.
func ByRegexUpdate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegexUpdate, opts...).ToFunc()
}

// ByIsAutoEnvEnable orders the results by the is_auto_env_enable field.
func ByIsAutoEnvEnable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAutoEnvEnable, opts...).ToFunc()
}

// ByEnableKey orders the results by the enable_key field.
func ByEnableKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnableKey, opts...).ToFunc()
}

// ByCdkLimit orders the results by the cdk_limit field.
func ByCdkLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCdkLimit, opts...).ToFunc()
}

// ByIsPrompt orders the results by the is_prompt field.
func ByIsPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPrompt, opts...).ToFunc()
}

// ByPromptLevel orders the results by the prompt_level field.
func ByPromptLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptLevel, opts...).ToFunc()
}

// ByPromptContent orders the results by the prompt_content field.
func ByPromptContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptContent, opts...).ToFunc()
}

// ByIsEnable orders the results by the is_enable field.
func ByIsEnable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEnable, opts...).ToFunc()
}

// ByPanelsCount orders the results by panels count.
func ByPanelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPanelsStep(), opts...)
	}
}

// ByPanels orders the results by panels terms.
func ByPanels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPanelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEnvPluginsCount orders the results by env_plugins count.
func ByEnvPluginsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEnvPluginsStep(), opts...)
	}
}

// ByEnvPlugins orders the results by env_plugins terms.
func ByEnvPlugins(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEnvPluginsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPanelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PanelsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, PanelsTable, PanelsPrimaryKey...),
	)
}
func newEnvPluginsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EnvPluginsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EnvPluginsTable, EnvPluginsColumn),
	)
}
