// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEnvPanels = "env_panels"

// EnvPanels Env 与 Panel 多对多关系表
type EnvPanels struct {
	EnvID   int64 `gorm:"column:env_id;type:bigint unsigned;primaryKey" json:"env_id"`
	PanelID int64 `gorm:"column:panel_id;type:bigint unsigned;primaryKey;index:fk_env_panels_panel,priority:1" json:"panel_id"`
}

// TableName EnvPanels's table name
func (*EnvPanels) TableName() string {
	return TableNameEnvPanels
}
