// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameEnvs = "envs"

// Envs Env 变量数据
type Envs struct {
	ID            int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                     // 主键ID
	CreatedAt     time.Time      `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_deleted_at,priority:1;comment:删除时间" json:"deleted_at"`       // 删除时间
	Name          string         `gorm:"column:name;type:varchar(255);not null;comment:名称" json:"name"`                                           // 名称
	Remarks       *string        `gorm:"column:remarks;type:varchar(255);comment:备注" json:"remarks"`                                              // 备注
	Quantity      int32          `gorm:"column:quantity;type:int;not null;comment:负载数量" json:"quantity"`                                          // 负载数量
	Regex         *string        `gorm:"column:regex;type:text;comment:匹配正则" json:"regex"`                                                        // 匹配正则
	Mode          int32          `gorm:"column:mode;type:int;not null;comment:模式" json:"mode"`                                                    // 模式
	RegexUpdate   *string        `gorm:"column:regex_update;type:text;comment:匹配正则[更新]" json:"regex_update"`                                      // 匹配正则[更新]
	EnableKey     bool           `gorm:"column:enable_key;type:tinyint(1);not null;comment:是否启用KEY" json:"enable_key"`                            // 是否启用KEY
	IsPrompt      bool           `gorm:"column:is_prompt;type:tinyint(1);not null;comment:是否提示" json:"is_prompt"`                                 // 是否提示
	PromptLevel   *string        `gorm:"column:prompt_level;type:varchar(255);comment:提示等级" json:"prompt_level"`                                  // 提示等级
	PromptContent *string        `gorm:"column:prompt_content;type:text;comment:提示内容" json:"prompt_content"`                                      // 提示内容
	IsEnable      bool           `gorm:"column:is_enable;type:tinyint(1);not null;comment:是否启用" json:"is_enable"`                                 // 是否启用
}

// TableName Envs's table name
func (*Envs) TableName() string {
	return TableNameEnvs
}
