// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePlugins = "plugins"

// Plugins 插件表
type Plugins struct {
	ID               int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                         // 主键ID
	CreatedAt        time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"`                                     // 创建时间
	UpdatedAt        time.Time `gorm:"column:updated_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"`                                     // 更新时间
	Name             string    `gorm:"column:name;type:varchar(255);not null;uniqueIndex:uk_name,priority:1;comment:插件名称" json:"name"`                                              // 插件名称
	Description      *string   `gorm:"column:description;type:text;comment:插件描述" json:"description"`                                                                                // 插件描述
	Version          string    `gorm:"column:version;type:varchar(50);not null;default:1.0.0;comment:插件版本" json:"version"`                                                          // 插件版本
	Author           *string   `gorm:"column:author;type:varchar(255);comment:插件作者" json:"author"`                                                                                  // 插件作者
	ScriptContent    string    `gorm:"column:script_content;type:longtext;not null;comment:JavaScript脚本内容" json:"script_content"`                                                   // JavaScript脚本内容
	IsEnable         bool      `gorm:"column:is_enable;type:tinyint(1);not null;index:idx_is_enable,priority:1;default:1;comment:是否启用" json:"is_enable"`                            // 是否启用
	ExecutionTimeout int32     `gorm:"column:execution_timeout;type:int;not null;default:10000;comment:执行超时时间(毫秒)" json:"execution_timeout"`                                        // 执行超时时间(毫秒)
	Category         *string   `gorm:"column:category;type:varchar(100);index:idx_category,priority:1;default:validator;comment:插件类别(validator:验证器,processor:处理器)" json:"category"` // 插件类别(validator:验证器,processor:处理器)
}

// TableName Plugins's table name
func (*Plugins) TableName() string {
	return TableNamePlugins
}
