// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUsers = "users"

// Users User 用户数据
type Users struct {
	ID        int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                     // 主键ID
	CreatedAt time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
	Username  string    `gorm:"column:username;type:varchar(255);not null;comment:用户名" json:"username"`                                  // 用户名
	Password  string    `gorm:"column:password;type:varchar(255);not null;comment:密码" json:"password"`                                   // 密码
}

// TableName Users's table name
func (*Users) TableName() string {
	return TableNameUsers
}
