// Code generated by ent, DO NOT EDIT.

package pluginexecutionlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldCreatedAt, v))
}

// PluginID applies equality check predicate on the "plugin_id" field. It's identical to PluginIDEQ.
func PluginID(v int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldPluginID, v))
}

// EnvID applies equality check predicate on the "env_id" field. It's identical to EnvIDEQ.
func EnvID(v int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldEnvID, v))
}

// ExecutionStatus applies equality check predicate on the "execution_status" field. It's identical to ExecutionStatusEQ.
func ExecutionStatus(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldExecutionStatus, v))
}

// ExecutionTime applies equality check predicate on the "execution_time" field. It's identical to ExecutionTimeEQ.
func ExecutionTime(v int32) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldExecutionTime, v))
}

// InputData applies equality check predicate on the "input_data" field. It's identical to InputDataEQ.
func InputData(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldInputData, v))
}

// OutputData applies equality check predicate on the "output_data" field. It's identical to OutputDataEQ.
func OutputData(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldOutputData, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldErrorMessage, v))
}

// StackTrace applies equality check predicate on the "stack_trace" field. It's identical to StackTraceEQ.
func StackTrace(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldStackTrace, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLTE(FieldCreatedAt, v))
}

// PluginIDEQ applies the EQ predicate on the "plugin_id" field.
func PluginIDEQ(v int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldPluginID, v))
}

// PluginIDNEQ applies the NEQ predicate on the "plugin_id" field.
func PluginIDNEQ(v int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNEQ(FieldPluginID, v))
}

// PluginIDIn applies the In predicate on the "plugin_id" field.
func PluginIDIn(vs ...int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIn(FieldPluginID, vs...))
}

// PluginIDNotIn applies the NotIn predicate on the "plugin_id" field.
func PluginIDNotIn(vs ...int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotIn(FieldPluginID, vs...))
}

// EnvIDEQ applies the EQ predicate on the "env_id" field.
func EnvIDEQ(v int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldEnvID, v))
}

// EnvIDNEQ applies the NEQ predicate on the "env_id" field.
func EnvIDNEQ(v int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNEQ(FieldEnvID, v))
}

// EnvIDIn applies the In predicate on the "env_id" field.
func EnvIDIn(vs ...int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIn(FieldEnvID, vs...))
}

// EnvIDNotIn applies the NotIn predicate on the "env_id" field.
func EnvIDNotIn(vs ...int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotIn(FieldEnvID, vs...))
}

// EnvIDGT applies the GT predicate on the "env_id" field.
func EnvIDGT(v int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGT(FieldEnvID, v))
}

// EnvIDGTE applies the GTE predicate on the "env_id" field.
func EnvIDGTE(v int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGTE(FieldEnvID, v))
}

// EnvIDLT applies the LT predicate on the "env_id" field.
func EnvIDLT(v int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLT(FieldEnvID, v))
}

// EnvIDLTE applies the LTE predicate on the "env_id" field.
func EnvIDLTE(v int64) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLTE(FieldEnvID, v))
}

// ExecutionStatusEQ applies the EQ predicate on the "execution_status" field.
func ExecutionStatusEQ(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldExecutionStatus, v))
}

// ExecutionStatusNEQ applies the NEQ predicate on the "execution_status" field.
func ExecutionStatusNEQ(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNEQ(FieldExecutionStatus, v))
}

// ExecutionStatusIn applies the In predicate on the "execution_status" field.
func ExecutionStatusIn(vs ...string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIn(FieldExecutionStatus, vs...))
}

// ExecutionStatusNotIn applies the NotIn predicate on the "execution_status" field.
func ExecutionStatusNotIn(vs ...string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotIn(FieldExecutionStatus, vs...))
}

// ExecutionStatusGT applies the GT predicate on the "execution_status" field.
func ExecutionStatusGT(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGT(FieldExecutionStatus, v))
}

// ExecutionStatusGTE applies the GTE predicate on the "execution_status" field.
func ExecutionStatusGTE(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGTE(FieldExecutionStatus, v))
}

// ExecutionStatusLT applies the LT predicate on the "execution_status" field.
func ExecutionStatusLT(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLT(FieldExecutionStatus, v))
}

// ExecutionStatusLTE applies the LTE predicate on the "execution_status" field.
func ExecutionStatusLTE(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLTE(FieldExecutionStatus, v))
}

// ExecutionStatusContains applies the Contains predicate on the "execution_status" field.
func ExecutionStatusContains(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldContains(FieldExecutionStatus, v))
}

// ExecutionStatusHasPrefix applies the HasPrefix predicate on the "execution_status" field.
func ExecutionStatusHasPrefix(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldHasPrefix(FieldExecutionStatus, v))
}

// ExecutionStatusHasSuffix applies the HasSuffix predicate on the "execution_status" field.
func ExecutionStatusHasSuffix(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldHasSuffix(FieldExecutionStatus, v))
}

// ExecutionStatusEqualFold applies the EqualFold predicate on the "execution_status" field.
func ExecutionStatusEqualFold(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEqualFold(FieldExecutionStatus, v))
}

// ExecutionStatusContainsFold applies the ContainsFold predicate on the "execution_status" field.
func ExecutionStatusContainsFold(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldContainsFold(FieldExecutionStatus, v))
}

// ExecutionTimeEQ applies the EQ predicate on the "execution_time" field.
func ExecutionTimeEQ(v int32) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldExecutionTime, v))
}

// ExecutionTimeNEQ applies the NEQ predicate on the "execution_time" field.
func ExecutionTimeNEQ(v int32) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNEQ(FieldExecutionTime, v))
}

// ExecutionTimeIn applies the In predicate on the "execution_time" field.
func ExecutionTimeIn(vs ...int32) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIn(FieldExecutionTime, vs...))
}

// ExecutionTimeNotIn applies the NotIn predicate on the "execution_time" field.
func ExecutionTimeNotIn(vs ...int32) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotIn(FieldExecutionTime, vs...))
}

// ExecutionTimeGT applies the GT predicate on the "execution_time" field.
func ExecutionTimeGT(v int32) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGT(FieldExecutionTime, v))
}

// ExecutionTimeGTE applies the GTE predicate on the "execution_time" field.
func ExecutionTimeGTE(v int32) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGTE(FieldExecutionTime, v))
}

// ExecutionTimeLT applies the LT predicate on the "execution_time" field.
func ExecutionTimeLT(v int32) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLT(FieldExecutionTime, v))
}

// ExecutionTimeLTE applies the LTE predicate on the "execution_time" field.
func ExecutionTimeLTE(v int32) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLTE(FieldExecutionTime, v))
}

// InputDataEQ applies the EQ predicate on the "input_data" field.
func InputDataEQ(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldInputData, v))
}

// InputDataNEQ applies the NEQ predicate on the "input_data" field.
func InputDataNEQ(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNEQ(FieldInputData, v))
}

// InputDataIn applies the In predicate on the "input_data" field.
func InputDataIn(vs ...string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIn(FieldInputData, vs...))
}

// InputDataNotIn applies the NotIn predicate on the "input_data" field.
func InputDataNotIn(vs ...string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotIn(FieldInputData, vs...))
}

// InputDataGT applies the GT predicate on the "input_data" field.
func InputDataGT(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGT(FieldInputData, v))
}

// InputDataGTE applies the GTE predicate on the "input_data" field.
func InputDataGTE(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGTE(FieldInputData, v))
}

// InputDataLT applies the LT predicate on the "input_data" field.
func InputDataLT(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLT(FieldInputData, v))
}

// InputDataLTE applies the LTE predicate on the "input_data" field.
func InputDataLTE(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLTE(FieldInputData, v))
}

// InputDataContains applies the Contains predicate on the "input_data" field.
func InputDataContains(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldContains(FieldInputData, v))
}

// InputDataHasPrefix applies the HasPrefix predicate on the "input_data" field.
func InputDataHasPrefix(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldHasPrefix(FieldInputData, v))
}

// InputDataHasSuffix applies the HasSuffix predicate on the "input_data" field.
func InputDataHasSuffix(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldHasSuffix(FieldInputData, v))
}

// InputDataIsNil applies the IsNil predicate on the "input_data" field.
func InputDataIsNil() predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIsNull(FieldInputData))
}

// InputDataNotNil applies the NotNil predicate on the "input_data" field.
func InputDataNotNil() predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotNull(FieldInputData))
}

// InputDataEqualFold applies the EqualFold predicate on the "input_data" field.
func InputDataEqualFold(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEqualFold(FieldInputData, v))
}

// InputDataContainsFold applies the ContainsFold predicate on the "input_data" field.
func InputDataContainsFold(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldContainsFold(FieldInputData, v))
}

// OutputDataEQ applies the EQ predicate on the "output_data" field.
func OutputDataEQ(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldOutputData, v))
}

// OutputDataNEQ applies the NEQ predicate on the "output_data" field.
func OutputDataNEQ(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNEQ(FieldOutputData, v))
}

// OutputDataIn applies the In predicate on the "output_data" field.
func OutputDataIn(vs ...string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIn(FieldOutputData, vs...))
}

// OutputDataNotIn applies the NotIn predicate on the "output_data" field.
func OutputDataNotIn(vs ...string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotIn(FieldOutputData, vs...))
}

// OutputDataGT applies the GT predicate on the "output_data" field.
func OutputDataGT(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGT(FieldOutputData, v))
}

// OutputDataGTE applies the GTE predicate on the "output_data" field.
func OutputDataGTE(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGTE(FieldOutputData, v))
}

// OutputDataLT applies the LT predicate on the "output_data" field.
func OutputDataLT(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLT(FieldOutputData, v))
}

// OutputDataLTE applies the LTE predicate on the "output_data" field.
func OutputDataLTE(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLTE(FieldOutputData, v))
}

// OutputDataContains applies the Contains predicate on the "output_data" field.
func OutputDataContains(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldContains(FieldOutputData, v))
}

// OutputDataHasPrefix applies the HasPrefix predicate on the "output_data" field.
func OutputDataHasPrefix(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldHasPrefix(FieldOutputData, v))
}

// OutputDataHasSuffix applies the HasSuffix predicate on the "output_data" field.
func OutputDataHasSuffix(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldHasSuffix(FieldOutputData, v))
}

// OutputDataIsNil applies the IsNil predicate on the "output_data" field.
func OutputDataIsNil() predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIsNull(FieldOutputData))
}

// OutputDataNotNil applies the NotNil predicate on the "output_data" field.
func OutputDataNotNil() predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotNull(FieldOutputData))
}

// OutputDataEqualFold applies the EqualFold predicate on the "output_data" field.
func OutputDataEqualFold(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEqualFold(FieldOutputData, v))
}

// OutputDataContainsFold applies the ContainsFold predicate on the "output_data" field.
func OutputDataContainsFold(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldContainsFold(FieldOutputData, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// StackTraceEQ applies the EQ predicate on the "stack_trace" field.
func StackTraceEQ(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEQ(FieldStackTrace, v))
}

// StackTraceNEQ applies the NEQ predicate on the "stack_trace" field.
func StackTraceNEQ(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNEQ(FieldStackTrace, v))
}

// StackTraceIn applies the In predicate on the "stack_trace" field.
func StackTraceIn(vs ...string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIn(FieldStackTrace, vs...))
}

// StackTraceNotIn applies the NotIn predicate on the "stack_trace" field.
func StackTraceNotIn(vs ...string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotIn(FieldStackTrace, vs...))
}

// StackTraceGT applies the GT predicate on the "stack_trace" field.
func StackTraceGT(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGT(FieldStackTrace, v))
}

// StackTraceGTE applies the GTE predicate on the "stack_trace" field.
func StackTraceGTE(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldGTE(FieldStackTrace, v))
}

// StackTraceLT applies the LT predicate on the "stack_trace" field.
func StackTraceLT(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLT(FieldStackTrace, v))
}

// StackTraceLTE applies the LTE predicate on the "stack_trace" field.
func StackTraceLTE(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldLTE(FieldStackTrace, v))
}

// StackTraceContains applies the Contains predicate on the "stack_trace" field.
func StackTraceContains(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldContains(FieldStackTrace, v))
}

// StackTraceHasPrefix applies the HasPrefix predicate on the "stack_trace" field.
func StackTraceHasPrefix(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldHasPrefix(FieldStackTrace, v))
}

// StackTraceHasSuffix applies the HasSuffix predicate on the "stack_trace" field.
func StackTraceHasSuffix(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldHasSuffix(FieldStackTrace, v))
}

// StackTraceIsNil applies the IsNil predicate on the "stack_trace" field.
func StackTraceIsNil() predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldIsNull(FieldStackTrace))
}

// StackTraceNotNil applies the NotNil predicate on the "stack_trace" field.
func StackTraceNotNil() predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldNotNull(FieldStackTrace))
}

// StackTraceEqualFold applies the EqualFold predicate on the "stack_trace" field.
func StackTraceEqualFold(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldEqualFold(FieldStackTrace, v))
}

// StackTraceContainsFold applies the ContainsFold predicate on the "stack_trace" field.
func StackTraceContainsFold(v string) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.FieldContainsFold(FieldStackTrace, v))
}

// HasPlugin applies the HasEdge predicate on the "plugin" edge.
func HasPlugin() predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PluginTable, PluginColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPluginWith applies the HasEdge predicate on the "plugin" edge with a given conditions (other predicates).
func HasPluginWith(preds ...predicate.Plugin) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(func(s *sql.Selector) {
		step := newPluginStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PluginExecutionLog) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PluginExecutionLog) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PluginExecutionLog) predicate.PluginExecutionLog {
	return predicate.PluginExecutionLog(sql.NotPredicates(p))
}
