// Code generated by ent, DO NOT EDIT.

package envplugin

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/nuanxinqing123/QLToolsV2/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldUpdatedAt, v))
}

// EnvID applies equality check predicate on the "env_id" field. It's identical to EnvIDEQ.
func EnvID(v int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldEnvID, v))
}

// PluginID applies equality check predicate on the "plugin_id" field. It's identical to PluginIDEQ.
func PluginID(v int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldPluginID, v))
}

// IsEnable applies equality check predicate on the "is_enable" field. It's identical to IsEnableEQ.
func IsEnable(v bool) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldIsEnable, v))
}

// ExecutionOrder applies equality check predicate on the "execution_order" field. It's identical to ExecutionOrderEQ.
func ExecutionOrder(v int32) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldExecutionOrder, v))
}

// Config applies equality check predicate on the "config" field. It's identical to ConfigEQ.
func Config(v string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldConfig, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldLTE(FieldUpdatedAt, v))
}

// EnvIDEQ applies the EQ predicate on the "env_id" field.
func EnvIDEQ(v int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldEnvID, v))
}

// EnvIDNEQ applies the NEQ predicate on the "env_id" field.
func EnvIDNEQ(v int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNEQ(FieldEnvID, v))
}

// EnvIDIn applies the In predicate on the "env_id" field.
func EnvIDIn(vs ...int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldIn(FieldEnvID, vs...))
}

// EnvIDNotIn applies the NotIn predicate on the "env_id" field.
func EnvIDNotIn(vs ...int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNotIn(FieldEnvID, vs...))
}

// PluginIDEQ applies the EQ predicate on the "plugin_id" field.
func PluginIDEQ(v int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldPluginID, v))
}

// PluginIDNEQ applies the NEQ predicate on the "plugin_id" field.
func PluginIDNEQ(v int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNEQ(FieldPluginID, v))
}

// PluginIDIn applies the In predicate on the "plugin_id" field.
func PluginIDIn(vs ...int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldIn(FieldPluginID, vs...))
}

// PluginIDNotIn applies the NotIn predicate on the "plugin_id" field.
func PluginIDNotIn(vs ...int64) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNotIn(FieldPluginID, vs...))
}

// IsEnableEQ applies the EQ predicate on the "is_enable" field.
func IsEnableEQ(v bool) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldIsEnable, v))
}

// IsEnableNEQ applies the NEQ predicate on the "is_enable" field.
func IsEnableNEQ(v bool) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNEQ(FieldIsEnable, v))
}

// ExecutionOrderEQ applies the EQ predicate on the "execution_order" field.
func ExecutionOrderEQ(v int32) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldExecutionOrder, v))
}

// ExecutionOrderNEQ applies the NEQ predicate on the "execution_order" field.
func ExecutionOrderNEQ(v int32) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNEQ(FieldExecutionOrder, v))
}

// ExecutionOrderIn applies the In predicate on the "execution_order" field.
func ExecutionOrderIn(vs ...int32) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldIn(FieldExecutionOrder, vs...))
}

// ExecutionOrderNotIn applies the NotIn predicate on the "execution_order" field.
func ExecutionOrderNotIn(vs ...int32) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNotIn(FieldExecutionOrder, vs...))
}

// ExecutionOrderGT applies the GT predicate on the "execution_order" field.
func ExecutionOrderGT(v int32) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldGT(FieldExecutionOrder, v))
}

// ExecutionOrderGTE applies the GTE predicate on the "execution_order" field.
func ExecutionOrderGTE(v int32) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldGTE(FieldExecutionOrder, v))
}

// ExecutionOrderLT applies the LT predicate on the "execution_order" field.
func ExecutionOrderLT(v int32) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldLT(FieldExecutionOrder, v))
}

// ExecutionOrderLTE applies the LTE predicate on the "execution_order" field.
func ExecutionOrderLTE(v int32) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldLTE(FieldExecutionOrder, v))
}

// ConfigEQ applies the EQ predicate on the "config" field.
func ConfigEQ(v string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEQ(FieldConfig, v))
}

// ConfigNEQ applies the NEQ predicate on the "config" field.
func ConfigNEQ(v string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNEQ(FieldConfig, v))
}

// ConfigIn applies the In predicate on the "config" field.
func ConfigIn(vs ...string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldIn(FieldConfig, vs...))
}

// ConfigNotIn applies the NotIn predicate on the "config" field.
func ConfigNotIn(vs ...string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNotIn(FieldConfig, vs...))
}

// ConfigGT applies the GT predicate on the "config" field.
func ConfigGT(v string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldGT(FieldConfig, v))
}

// ConfigGTE applies the GTE predicate on the "config" field.
func ConfigGTE(v string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldGTE(FieldConfig, v))
}

// ConfigLT applies the LT predicate on the "config" field.
func ConfigLT(v string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldLT(FieldConfig, v))
}

// ConfigLTE applies the LTE predicate on the "config" field.
func ConfigLTE(v string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldLTE(FieldConfig, v))
}

// ConfigContains applies the Contains predicate on the "config" field.
func ConfigContains(v string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldContains(FieldConfig, v))
}

// ConfigHasPrefix applies the HasPrefix predicate on the "config" field.
func ConfigHasPrefix(v string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldHasPrefix(FieldConfig, v))
}

// ConfigHasSuffix applies the HasSuffix predicate on the "config" field.
func ConfigHasSuffix(v string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldHasSuffix(FieldConfig, v))
}

// ConfigIsNil applies the IsNil predicate on the "config" field.
func ConfigIsNil() predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldIsNull(FieldConfig))
}

// ConfigNotNil applies the NotNil predicate on the "config" field.
func ConfigNotNil() predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldNotNull(FieldConfig))
}

// ConfigEqualFold applies the EqualFold predicate on the "config" field.
func ConfigEqualFold(v string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldEqualFold(FieldConfig, v))
}

// ConfigContainsFold applies the ContainsFold predicate on the "config" field.
func ConfigContainsFold(v string) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.FieldContainsFold(FieldConfig, v))
}

// HasEnv applies the HasEdge predicate on the "env" edge.
func HasEnv() predicate.EnvPlugin {
	return predicate.EnvPlugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EnvTable, EnvColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEnvWith applies the HasEdge predicate on the "env" edge with a given conditions (other predicates).
func HasEnvWith(preds ...predicate.Env) predicate.EnvPlugin {
	return predicate.EnvPlugin(func(s *sql.Selector) {
		step := newEnvStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlugin applies the HasEdge predicate on the "plugin" edge.
func HasPlugin() predicate.EnvPlugin {
	return predicate.EnvPlugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PluginTable, PluginColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPluginWith applies the HasEdge predicate on the "plugin" edge with a given conditions (other predicates).
func HasPluginWith(preds ...predicate.Plugin) predicate.EnvPlugin {
	return predicate.EnvPlugin(func(s *sql.Selector) {
		step := newPluginStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EnvPlugin) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EnvPlugin) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EnvPlugin) predicate.EnvPlugin {
	return predicate.EnvPlugin(sql.NotPredicates(p))
}
