basePath: /api
definitions:
  response.Data:
    properties:
      code:
        $ref: '#/definitions/response.ResCode'
      data: {}
      msg: {}
    type: object
  response.ResCode:
    enum:
    - 20000
    format: int64
    type: integer
    x-enum-varnames:
    - CodeSuccess
  schema.AddPanelRequest:
    properties:
      client_id:
        description: Client_ID
        type: string
      client_secret:
        description: Client_Secret
        type: string
      name:
        description: 面板名称
        type: string
      url:
        description: 连接地址
        type: string
    required:
    - client_id
    - client_secret
    - name
    - url
    type: object
  schema.AddPanelResponse:
    properties:
      id:
        description: 面板ID
        type: integer
      message:
        description: 消息
        type: string
    type: object
  schema.DeletePanelResponse:
    properties:
      message:
        description: 消息
        type: string
    type: object
  schema.GetCaptchaResponse:
    properties:
      captcha_base64:
        description: 验证码图片Base64
        type: string
      captcha_id:
        description: 验证码ID
        type: string
    type: object
  schema.GetPanelListResponse:
    properties:
      list:
        description: 面板列表
        items:
          $ref: '#/definitions/schema.GetPanelResponse'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  schema.GetPanelResponse:
    properties:
      client_id:
        description: Client_ID
        type: string
      client_secret:
        description: Client_Secret（敏感信息，可考虑脱敏）
        type: string
      created_at:
        description: 创建时间
        type: string
      id:
        description: 面板ID
        type: integer
      is_enable:
        description: 是否启用
        type: boolean
      name:
        description: 面板名称
        type: string
      params:
        description: Params
        type: integer
      token:
        description: Token
        type: string
      updated_at:
        description: 更新时间
        type: string
      url:
        description: 连接地址
        type: string
    type: object
  schema.LoginRequest:
    properties:
      captcha_code:
        description: 验证码
        type: string
      captcha_id:
        description: 验证码ID
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - captcha_code
    - captcha_id
    - password
    - username
    type: object
  schema.LoginResponse:
    properties:
      access_token:
        description: 访问令牌
        type: string
      message:
        description: 消息
        type: string
      refresh_token:
        description: 刷新令牌
        type: string
    type: object
  schema.LogoutResponse:
    properties:
      message:
        description: 消息
        type: string
    type: object
  schema.RefreshPanelTokenRequest:
    properties:
      id:
        description: 面板ID
        type: integer
    required:
    - id
    type: object
  schema.RefreshPanelTokenResponse:
    properties:
      message:
        description: 消息
        type: string
      token:
        description: 新Token
        type: string
    type: object
  schema.RefreshTokenRequest:
    properties:
      refresh_token:
        description: 刷新Token
        type: string
    required:
    - refresh_token
    type: object
  schema.RefreshTokenResponse:
    properties:
      access_token:
        description: 访问令牌
        type: string
      message:
        description: 消息
        type: string
    type: object
  schema.RegisterRequest:
    properties:
      captcha_code:
        description: 验证码
        type: string
      captcha_id:
        description: 验证码ID
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - captcha_code
    - captcha_id
    - password
    - username
    type: object
  schema.RegisterResponse:
    properties:
      message:
        description: 消息
        type: string
    type: object
  schema.TogglePanelStatusRequest:
    properties:
      id:
        description: 面板ID
        type: integer
      is_enable:
        description: 是否启用
        type: boolean
    required:
    - id
    - is_enable
    type: object
  schema.TogglePanelStatusResponse:
    properties:
      message:
        description: 消息
        type: string
    type: object
  schema.UpdatePanelRequest:
    properties:
      client_id:
        description: Client_ID
        type: string
      client_secret:
        description: Client_Secret
        type: string
      id:
        description: 面板ID
        type: integer
      is_enable:
        description: 是否启用（可选）
        type: boolean
      name:
        description: 面板名称
        type: string
      url:
        description: 连接地址
        type: string
    required:
    - client_id
    - client_secret
    - id
    - name
    - url
    type: object
  schema.UpdatePanelResponse:
    properties:
      message:
        description: 消息
        type: string
    type: object
host: localhost:1500
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: https://www.swagger.io/support
  description: 青龙ToolsV2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://swagger.io/terms/
  title: QLToolsV2
  version: "1.0"
paths:
  /api/auth/captcha:
    get:
      consumes:
      - application/json
      description: 生成算术验证码并返回验证码ID与Base64图片
      produces:
      - application/json
      responses:
        "200":
          description: 验证码信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/schema.GetCaptchaResponse'
              type: object
        "500":
          description: 验证码生成失败
          schema:
            $ref: '#/definitions/response.Data'
      summary: 获取验证码
      tags:
      - 认证管理
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: 用户登录接口，需要验证码验证，返回访问令牌和刷新令牌
      parameters:
      - description: 登录请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/schema.LoginResponse'
              type: object
        "400":
          description: 请求参数错误或验证码错误
          schema:
            $ref: '#/definitions/response.Data'
        "401":
          description: 认证失败
          schema:
            $ref: '#/definitions/response.Data'
      summary: 用户登录
      tags:
      - 认证管理
  /api/auth/logout:
    post:
      consumes:
      - application/json
      description: 用户登出接口，注销当前用户的访问令牌
      produces:
      - application/json
      responses:
        "200":
          description: 登出成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/schema.LogoutResponse'
              type: object
        "401":
          description: 需要登录
          schema:
            $ref: '#/definitions/response.Data'
        "500":
          description: 登出失败
          schema:
            $ref: '#/definitions/response.Data'
      security:
      - ApiKeyAuth: []
      summary: 用户登出
      tags:
      - 认证管理
  /api/auth/refresh:
    post:
      consumes:
      - application/json
      description: 使用刷新令牌获取新的访问令牌
      parameters:
      - description: 刷新令牌请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 刷新成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/schema.RefreshTokenResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Data'
        "401":
          description: 刷新令牌无效
          schema:
            $ref: '#/definitions/response.Data'
      summary: 刷新访问令牌
      tags:
      - 认证管理
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: 用户注册接口，需要验证码验证
      parameters:
      - description: 注册请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/schema.RegisterResponse'
              type: object
        "400":
          description: 请求参数错误或验证码错误
          schema:
            $ref: '#/definitions/response.Data'
        "500":
          description: 注册失败
          schema:
            $ref: '#/definitions/response.Data'
      summary: 用户注册
      tags:
      - 认证管理
  /api/panel/{id}:
    delete:
      consumes:
      - application/json
      description: 根据面板ID删除面板（软删除）
      parameters:
      - description: 面板ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/schema.DeletePanelResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Data'
        "404":
          description: 面板不存在
          schema:
            $ref: '#/definitions/response.Data'
        "500":
          description: 删除失败
          schema:
            $ref: '#/definitions/response.Data'
      security:
      - ApiKeyAuth: []
      summary: 删除面板
      tags:
      - 面板管理
    get:
      consumes:
      - application/json
      description: 根据面板ID获取面板详细信息
      parameters:
      - description: 面板ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/schema.GetPanelResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Data'
        "404":
          description: 面板不存在
          schema:
            $ref: '#/definitions/response.Data'
        "500":
          description: 获取失败
          schema:
            $ref: '#/definitions/response.Data'
      security:
      - ApiKeyAuth: []
      summary: 获取面板信息
      tags:
      - 面板管理
  /api/panel/create:
    post:
      consumes:
      - application/json
      description: 添加新的面板配置，需要提供面板名称、连接地址、Client_ID和Client_Secret
      parameters:
      - description: 添加面板请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.AddPanelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 添加成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/schema.AddPanelResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Data'
        "500":
          description: 添加失败
          schema:
            $ref: '#/definitions/response.Data'
      security:
      - ApiKeyAuth: []
      summary: 添加面板
      tags:
      - 面板管理
  /api/panel/list:
    get:
      consumes:
      - application/json
      description: 分页获取面板列表，支持按名称搜索和状态筛选
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: page_size
        type: integer
      - description: 面板名称（模糊搜索）
        in: query
        name: name
        type: string
      - description: 是否启用
        in: query
        name: is_enable
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/schema.GetPanelListResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Data'
        "500":
          description: 获取失败
          schema:
            $ref: '#/definitions/response.Data'
      security:
      - ApiKeyAuth: []
      summary: 获取面板列表
      tags:
      - 面板管理
  /api/panel/refresh-token:
    post:
      consumes:
      - application/json
      description: 重新获取面板的访问Token
      parameters:
      - description: 刷新Token请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.RefreshPanelTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 刷新成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/schema.RefreshPanelTokenResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Data'
        "404":
          description: 面板不存在
          schema:
            $ref: '#/definitions/response.Data'
        "500":
          description: 刷新失败
          schema:
            $ref: '#/definitions/response.Data'
      security:
      - ApiKeyAuth: []
      summary: 刷新面板Token
      tags:
      - 面板管理
  /api/panel/toggle-status:
    post:
      consumes:
      - application/json
      description: 启用或禁用面板
      parameters:
      - description: 切换状态请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.TogglePanelStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 切换成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/schema.TogglePanelStatusResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Data'
        "404":
          description: 面板不存在
          schema:
            $ref: '#/definitions/response.Data'
        "500":
          description: 切换失败
          schema:
            $ref: '#/definitions/response.Data'
      security:
      - ApiKeyAuth: []
      summary: 切换面板状态
      tags:
      - 面板管理
  /api/panel/update:
    put:
      consumes:
      - application/json
      description: 更新面板配置信息
      parameters:
      - description: 更新面板请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.UpdatePanelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Data'
            - properties:
                data:
                  $ref: '#/definitions/schema.UpdatePanelResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Data'
        "404":
          description: 面板不存在
          schema:
            $ref: '#/definitions/response.Data'
        "500":
          description: 更新失败
          schema:
            $ref: '#/definitions/response.Data'
      security:
      - ApiKeyAuth: []
      summary: 更新面板
      tags:
      - 面板管理
securityDefinitions:
  ApiKeyAuth:
    description: Bearer token for API authentication
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
